/**
 * Expanded question bank — 100 hand-written questions added to grow the daily
 * and practice pools. Same shape and rules as the seed samples (spec §2.2):
 * every clue true of the answer; clues 1–2 also plausibly fit a decoy; each
 * later clue eliminates a decoy or adds recognizability; clue 4 is a fair
 * giveaway; no clue contains the answer or an obvious derivative.
 *
 * Style note: clue 1 is written crossword-terse — one oblique, surprising
 * fact rather than a descriptive paragraph — so a fast solver can leap on it
 * but a casual solver still needs the ladder. Clues 2–4 open up from there.
 *
 * These merge into the local bank after SEED_QUESTIONS and (when present) the
 * gitignored private bank. They are validated by the same integrity suite.
 */

import type { Question } from "@/lib/game/types";

export const EXTRA_QUESTIONS: Question[] = [
  {
    id: "saturn",
    answer: "Saturn",
    answerCanonical: "saturn",
    answerAliases: [],
    category: "Space",
    difficulty: "easy",
    clues: [
      { position: 1, text: "Less dense than water, it would float if you could find a bathtub big enough." },
      { position: 2, text: "It is not the only planet with rings, but its bright, icy bands are by far the widest and most spectacular in the Solar System." },
      { position: 3, text: "The sixth planet from the Sun, it takes about 29 Earth years to circle once and hosts a giant moon, Titan, with a thick orange atmosphere." },
      { position: 4, text: "This ringed gas giant lends its name to the day between Friday and Sunday." },
    ],
    decoys: [
      { text: "Jupiter", eliminatedByClue: 2 },
      { text: "Uranus", eliminatedByClue: 3 },
    ],
  },
  {
    id: "jupiter",
    answer: "Jupiter",
    answerCanonical: "jupiter",
    answerAliases: [],
    category: "Space",
    difficulty: "easy",
    clues: [
      { position: 1, text: "A single storm on it has raged for centuries and is wide enough to swallow the whole Earth." },
      { position: 2, text: "The largest planet in the Solar System, it is so massive that every other planet could fit inside it with room to spare." },
      { position: 3, text: "Galileo spotted its four biggest moons in 1610; one of them, Ganymede, is larger than the planet Mercury." },
      { position: 4, text: "The fifth planet from the Sun, this banded giant is named for the king of the Roman gods." },
    ],
    decoys: [
      { text: "Saturn", eliminatedByClue: 2 },
      { text: "Neptune", eliminatedByClue: 2 },
    ],
  },
  {
    id: "mars",
    answer: "Mars",
    answerCanonical: "mars",
    answerAliases: ["the Red Planet"],
    category: "Space",
    difficulty: "easy",
    clues: [
      { position: 1, text: "It boasts both the tallest volcano and one of the deepest canyons known anywhere in the Solar System." },
      { position: 2, text: "A cold desert world with a thin atmosphere, its rusty, iron-rich soil tints it a color you can spot with the naked eye." },
      { position: 3, text: "Two tiny lumpy moons, Phobos and Deimos, orbit it, and rovers named Curiosity and Perseverance roam its surface." },
      { position: 4, text: "The fourth planet from the Sun, this rusty neighbor of Earth is named for the Roman god of war." },
    ],
    decoys: [
      { text: "Mercury", eliminatedByClue: 2 },
      { text: "Venus", eliminatedByClue: 2 },
    ],
  },
  {
    id: "leonardo-da-vinci",
    answer: "Leonardo da Vinci",
    answerCanonical: "leonardo da vinci",
    answerAliases: ["da Vinci", "Leonardo"],
    category: "Art",
    difficulty: "medium",
    clues: [
      { position: 1, text: "He filled thousands of notebook pages with mirror writing, legible only when held up to a looking glass." },
      { position: 2, text: "A left-handed vegetarian, he sketched helicopters, tanks, and diving suits centuries before they could be built — and left many paintings unfinished." },
      { position: 3, text: "A defining genius of the Italian Renaissance, he painted a fresco of the Last Supper that began flaking off a Milan wall almost at once." },
      { position: 4, text: "This polymath's best-known work is a small portrait of a faintly smiling woman that hangs in the Louvre." },
    ],
    decoys: [
      { text: "Michelangelo", eliminatedByClue: 2 },
      { text: "Raphael", eliminatedByClue: 3 },
    ],
  },
  {
    id: "mona-lisa",
    answer: "Mona Lisa",
    answerCanonical: "mona lisa",
    answerAliases: ["La Gioconda", "La Joconde"],
    category: "Art",
    difficulty: "medium",
    clues: [
      { position: 1, text: "In 1911 a museum handyman walked out with it under his coat, and the bare wall it left behind drew even bigger crowds." },
      { position: 2, text: "Painted on a panel of poplar wood, this small portrait now sits behind bulletproof glass and is far tinier than most visitors expect." },
      { position: 3, text: "The sitter's ambiguous half-smile — and her missing eyebrows — have fueled centuries of speculation." },
      { position: 4, text: "Leonardo da Vinci's most celebrated portrait, it is the star attraction of the Louvre in Paris." },
    ],
    decoys: [
      { text: "The Night Watch", eliminatedByClue: 2 },
      { text: "Girl with a Pearl Earring", eliminatedByClue: 4 },
    ],
  },
  {
    id: "vincent-van-gogh",
    answer: "Vincent van Gogh",
    answerCanonical: "vincent van gogh",
    answerAliases: ["van Gogh"],
    category: "Art",
    difficulty: "medium",
    clues: [
      { position: 1, text: "He sold almost nothing while alive, yet poured out some 2,000 works in barely a decade." },
      { position: 2, text: "Tormented by mental illness, this Dutch painter famously cut off part of his own ear." },
      { position: 3, text: "His thick, swirling brushstrokes and blazing yellows fill canvases like 'Sunflowers' and a whirling night sky over a village." },
      { position: 4, text: "This red-haired Post-Impressionist, who painted 'The Starry Night,' died largely unknown and is now among the most beloved artists ever." },
    ],
    decoys: [
      { text: "Claude Monet", eliminatedByClue: 2 },
      { text: "Paul Gauguin", eliminatedByClue: 4 },
    ],
  },
  {
    id: "albert-einstein",
    answer: "Albert Einstein",
    answerCanonical: "albert einstein",
    answerAliases: ["Einstein"],
    category: "Science",
    difficulty: "medium",
    clues: [
      { position: 1, text: "His most famous theory never won him a Nobel Prize — the award instead cited his work on the photoelectric effect." },
      { position: 2, text: "This German-born physicist was offered the presidency of Israel in 1952 and politely declined." },
      { position: 3, text: "His theories of relativity overturned how we picture space, time, and gravity in the early 20th century." },
      { position: 4, text: "Known for the equation E=mc² and a mane of wild white hair, his surname is now shorthand for 'genius.'" },
    ],
    decoys: [
      { text: "Isaac Newton", eliminatedByClue: 3 },
      { text: "Stephen Hawking", eliminatedByClue: 2 },
    ],
  },
  {
    id: "isaac-newton",
    answer: "Isaac Newton",
    answerCanonical: "isaac newton",
    answerAliases: ["Newton"],
    category: "Science",
    difficulty: "medium",
    clues: [
      { position: 1, text: "He poured as many years into alchemy and biblical prophecy as into physics, and once ran a nation's mint, hanging counterfeiters." },
      { position: 2, text: "A prickly Englishman, he devised calculus around the same time as Leibniz, igniting a bitter priority feud." },
      { position: 3, text: "His three laws describe how objects move, and legend says a falling apple set off his thinking about gravity." },
      { position: 4, text: "This 17th-century scientist's masterwork, the 'Principia,' laid out universal gravitation; the SI unit of force carries his name." },
    ],
    decoys: [
      { text: "Galileo Galilei", eliminatedByClue: 2 },
      { text: "Albert Einstein", eliminatedByClue: 4 },
    ],
  },
  {
    id: "marie-curie",
    answer: "Marie Curie",
    answerCanonical: "marie curie",
    answerAliases: ["Curie", "Madame Curie"],
    category: "Science",
    difficulty: "medium",
    clues: [
      { position: 1, text: "She remains the only person ever to win Nobel Prizes in two different sciences." },
      { position: 2, text: "Her century-old notebooks are still so radioactive that they are stored in lead-lined boxes and handled with protective gear." },
      { position: 3, text: "Born in Poland and working in France, she discovered the elements polonium and radium." },
      { position: 4, text: "A pioneer of radioactivity, she was the first woman to win a Nobel Prize; her daughter Irène later earned one too." },
    ],
    decoys: [
      { text: "Rosalind Franklin", eliminatedByClue: 3 },
      { text: "Lise Meitner", eliminatedByClue: 1 },
    ],
  },
  {
    id: "mount-everest",
    answer: "Mount Everest",
    answerCanonical: "mount everest",
    answerAliases: ["Everest", "Sagarmatha", "Chomolungma"],
    category: "Geography",
    difficulty: "medium",
    clues: [
      { position: 1, text: "Its summit is not actually the spot on Earth's surface farthest from the planet's center — a peak in Ecuador wins that on a technicality." },
      { position: 2, text: "It creeps a few millimeters higher each year as two plates grind together, and its top sits in the 'death zone,' where the air is too thin to survive for long." },
      { position: 3, text: "Sitting on the border of Nepal and Tibet, it was first conquered in 1953 by Edmund Hillary and Tenzing Norgay." },
      { position: 4, text: "At about 8,849 meters, this Himalayan giant is the highest mountain on Earth above sea level." },
    ],
    decoys: [
      { text: "K2", eliminatedByClue: 3 },
      { text: "Mauna Kea", eliminatedByClue: 4 },
    ],
  },
  {
    id: "sahara-desert",
    answer: "Sahara Desert",
    answerCanonical: "sahara desert",
    answerAliases: ["Sahara", "the Sahara"],
    category: "Geography",
    difficulty: "medium",
    clues: [
      { position: 1, text: "Dust lifted from it blows clear across the Atlantic to fertilize the Amazon rainforest thousands of miles away." },
      { position: 2, text: "Roughly the size of the United States, it was dotted with lakes and grazing herds only a few thousand years ago." },
      { position: 3, text: "Sprawling across North Africa, it can broil by day and freeze by night, and has even seen a dusting of snow." },
      { position: 4, text: "This is the largest hot desert on Earth, its name meaning simply 'desert' in Arabic." },
    ],
    decoys: [
      { text: "Gobi Desert", eliminatedByClue: 3 },
      { text: "Kalahari Desert", eliminatedByClue: 4 },
    ],
  },
  {
    id: "antarctica",
    answer: "Antarctica",
    answerCanonical: "antarctica",
    answerAliases: [],
    category: "Geography",
    difficulty: "medium",
    clues: [
      { position: 1, text: "Technically the largest desert on the planet, it gets almost no precipitation despite being smothered in ice." },
      { position: 2, text: "No nation owns it, and it has no permanent residents — only rotating crews of scientists." },
      { position: 3, text: "It locks up about 70% of the world's fresh water as ice, and the coldest temperature ever recorded on Earth was measured here." },
      { position: 4, text: "Home to emperor penguins and the South Pole, it is the southernmost continent." },
    ],
    decoys: [
      { text: "Greenland", eliminatedByClue: 2 },
      { text: "The Arctic", eliminatedByClue: 4 },
    ],
  },
  {
    id: "niagara-falls",
    answer: "Niagara Falls",
    answerCanonical: "niagara falls",
    answerAliases: ["Niagara"],
    category: "Geography",
    difficulty: "medium",
    clues: [
      { position: 1, text: "In 1901 a 63-year-old schoolteacher rode over it sealed inside a wooden barrel — and lived." },
      { position: 2, text: "It briefly ran nearly dry in 1969 when engineers dammed its river to study the eroding rock face." },
      { position: 3, text: "Sitting on the border between the United States and Canada, it lures honeymooners and daredevils in equal measure." },
      { position: 4, text: "This trio of waterfalls, including Horseshoe Falls, straddles New York and Ontario and is among the most famous on Earth." },
    ],
    decoys: [
      { text: "Victoria Falls", eliminatedByClue: 3 },
      { text: "Angel Falls", eliminatedByClue: 4 },
    ],
  },
  {
    id: "great-barrier-reef",
    answer: "Great Barrier Reef",
    answerCanonical: "great barrier reef",
    answerAliases: ["the Great Barrier Reef"],
    category: "Nature",
    difficulty: "medium",
    clues: [
      { position: 1, text: "It is the largest structure on Earth made by living creatures, and is visible from space." },
      { position: 2, text: "Built by billions of tiny coral polyps over thousands of years, it turns ghostly white when warming seas make it 'bleach.'" },
      { position: 3, text: "Running more than 2,300 kilometers off the coast of Queensland, Australia, it shelters clownfish, sea turtles, and reef sharks." },
      { position: 4, text: "This is the world's largest coral reef system, lying off Australia's northeastern shore." },
    ],
    decoys: [
      { text: "Amazon Rainforest", eliminatedByClue: 2 },
      { text: "Belize Barrier Reef", eliminatedByClue: 3 },
    ],
  },
  {
    id: "grand-canyon",
    answer: "Grand Canyon",
    answerCanonical: "grand canyon",
    answerAliases: [],
    category: "Geography",
    difficulty: "easy",
    clues: [
      { position: 1, text: "Its walls expose nearly two billion years of Earth's past, yet the chasm itself was cut in only the last few million." },
      { position: 2, text: "Carved by the Colorado River in Arizona, it plunges more than a mile deep in places." },
      { position: 3, text: "A national park draws millions each year to watch the shifting light paint its banded red cliffs." },
      { position: 4, text: "This vast Arizona gorge, one of the Seven Natural Wonders of the World, is famed for its sheer size and layered walls." },
    ],
    decoys: [
      { text: "Zion Canyon", eliminatedByClue: 4 },
      { text: "Yosemite Valley", eliminatedByClue: 2 },
    ],
  },
  {
    id: "eiffel-tower",
    answer: "Eiffel Tower",
    answerCanonical: "eiffel tower",
    answerAliases: ["the Eiffel Tower"],
    category: "Landmarks",
    difficulty: "easy",
    clues: [
      { position: 1, text: "It stands more than 15 centimeters taller in summer, when the heat makes its iron expand." },
      { position: 2, text: "Built as a temporary showpiece for an 1889 world's fair, it was nearly scrapped but survived because it made a superb radio antenna." },
      { position: 3, text: "Its wrought-iron lattice is repainted every few years to hold back rust, and it towers over a European capital's skyline." },
      { position: 4, text: "This latticed iron landmark, raised for the 1889 Exposition in Paris, is one of the most visited monuments on Earth and a symbol of France." },
    ],
    decoys: [
      { text: "Empire State Building", eliminatedByClue: 3 },
      { text: "Statue of Liberty", eliminatedByClue: 4 },
    ],
  },
  {
    id: "colosseum",
    answer: "Colosseum",
    answerCanonical: "colosseum",
    answerAliases: ["the Colosseum", "Coliseum"],
    category: "Landmarks",
    difficulty: "medium",
    clues: [
      { position: 1, text: "It could reportedly be flooded to stage mock naval battles for the roaring crowds." },
      { position: 2, text: "Raised nearly 2,000 years ago, this vast stone arena packed in tens of thousands to watch gladiators fight." },
      { position: 3, text: "Battered by earthquakes and quarried for its stone over the centuries, its ruins still loom over a famous Italian capital." },
      { position: 4, text: "This ancient oval amphitheater is the single most iconic monument of Rome." },
    ],
    decoys: [
      { text: "Circus Maximus", eliminatedByClue: 1 },
      { text: "Pantheon", eliminatedByClue: 2 },
    ],
  },
  {
    id: "statue-of-liberty",
    answer: "Statue of Liberty",
    answerCanonical: "statue of liberty",
    answerAliases: ["Lady Liberty", "the Statue of Liberty"],
    category: "Landmarks",
    difficulty: "easy",
    clues: [
      { position: 1, text: "A gift between two nations, its copper skin was a shiny reddish brown before weather turned it the green we know." },
      { position: 2, text: "Its internal framework was engineered with help from Gustave Eiffel, and it crossed the Atlantic packed in 350 pieces." },
      { position: 3, text: "Rising from an island in New York Harbor, she lifts a torch in one hand and cradles a tablet marked with a date in Roman numerals." },
      { position: 4, text: "This robed figure, France's gift to America, greeted generations of immigrants sailing into New York." },
    ],
    decoys: [
      { text: "Christ the Redeemer", eliminatedByClue: 3 },
      { text: "Colossus of Rhodes", eliminatedByClue: 4 },
    ],
  },
  {
    id: "taj-mahal",
    answer: "Taj Mahal",
    answerCanonical: "taj mahal",
    answerAliases: ["the Taj Mahal"],
    category: "Landmarks",
    difficulty: "medium",
    clues: [
      { position: 1, text: "It seems to shift color through the day — blushing pink at dawn, white at noon, and golden by moonlight." },
      { position: 2, text: "A grieving emperor built it as a tomb for his beloved wife; some 20,000 workers labored on it for about two decades." },
      { position: 3, text: "Perfectly symmetrical and clad in white marble inlaid with gemstones, it rests beside the Yamuna River in Agra, India." },
      { position: 4, text: "This 17th-century mausoleum is India's most famous building and a jewel of Mughal architecture." },
    ],
    decoys: [
      { text: "Red Fort", eliminatedByClue: 2 },
      { text: "Angkor Wat", eliminatedByClue: 3 },
    ],
  },
  {
    id: "kangaroo",
    answer: "Kangaroo",
    answerCanonical: "kangaroo",
    answerAliases: ["kangaroos"],
    category: "Animals",
    difficulty: "easy",
    clues: [
      { position: 1, text: "It physically cannot walk backward, and springy tendons let it bound faster while burning less energy." },
      { position: 2, text: "A newborn is the size of a jellybean and hauls itself into its mother's pouch to keep developing." },
      { position: 3, text: "This marsupial props itself on a thick muscular tail like a fifth limb and can throw a bruising kick." },
      { position: 4, text: "Australia's famous hopping icon, the males are called boomers and the babies are joeys." },
    ],
    decoys: [
      { text: "Koala", eliminatedByClue: 1 },
      { text: "Wallaby", eliminatedByClue: 4 },
    ],
  },
  {
    id: "giant-panda",
    answer: "Giant Panda",
    answerCanonical: "giant panda",
    answerAliases: ["panda", "pandas"],
    category: "Animals",
    difficulty: "easy",
    clues: [
      { position: 1, text: "Though its gut is built like a meat-eater's, it spends up to 14 hours a day munching almost nothing but bamboo." },
      { position: 2, text: "A newborn is pink, hairless, and about the size of a stick of butter — roughly a nine-hundredth of its mother's weight." },
      { position: 3, text: "A 'thumb' formed from an enlarged wrist bone helps it grip stalks, and China lends these black-and-white bears to zoos abroad." },
      { position: 4, text: "This bamboo-eating bear from China's misty highlands is the black-and-white emblem of the WWF." },
    ],
    decoys: [
      { text: "Polar Bear", eliminatedByClue: 1 },
      { text: "Red Panda", eliminatedByClue: 3 },
    ],
  },
  {
    id: "chameleon",
    answer: "Chameleon",
    answerCanonical: "chameleon",
    answerAliases: ["chameleons"],
    category: "Animals",
    difficulty: "medium",
    clues: [
      { position: 1, text: "Its two eyes can swivel and aim in entirely different directions at the same instant." },
      { position: 2, text: "It fires out a tongue longer than its own body to snatch an insect, striking in a fraction of a second." },
      { position: 3, text: "Many species shift color less for camouflage than to broadcast mood and temperature, by rearranging tiny crystals in their skin." },
      { position: 4, text: "This lizard, with many kinds native to Madagascar, is famous for changing color and clamping onto branches with pincer-like feet." },
    ],
    decoys: [
      { text: "Gecko", eliminatedByClue: 3 },
      { text: "Octopus", eliminatedByClue: 4 },
    ],
  },
  {
    id: "honeybee",
    answer: "Honeybee",
    answerCanonical: "honeybee",
    answerAliases: ["honey bee", "honeybees", "honey-bee"],
    category: "Animals",
    difficulty: "easy",
    clues: [
      { position: 1, text: "It tells its sisters exactly where to find food by performing a looping 'waggle dance.'" },
      { position: 2, text: "A female worker can strike only once, because her barbed stinger tears free and the wound kills her." },
      { position: 3, text: "Living in colonies tens of thousands strong under a single queen, these insects build wax combs of six-sided cells." },
      { position: 4, text: "This buzzing pollinator turns flower nectar into the golden syrup we drizzle on toast." },
    ],
    decoys: [
      { text: "Wasp", eliminatedByClue: 4 },
      { text: "Bumblebee", eliminatedByClue: 2 },
    ],
  },
  {
    id: "elephant",
    answer: "Elephant",
    answerCanonical: "elephant",
    answerAliases: ["elephants"],
    category: "Animals",
    difficulty: "easy",
    clues: [
      { position: 1, text: "It is the only land mammal that cannot jump, yet it can 'hear' distant rumbles through the soles of its feet." },
      { position: 2, text: "Talking in calls too deep for us to hear, it can recognize itself in a mirror and seems to grieve over its dead." },
      { position: 3, text: "The largest land animal alive, it breathes, drinks, and grabs food with a long trunk packed with tens of thousands of muscles." },
      { position: 4, text: "This gray giant, with big flapping ears and ivory tusks, comes in African and Asian kinds." },
    ],
    decoys: [
      { text: "Rhinoceros", eliminatedByClue: 3 },
      { text: "Hippopotamus", eliminatedByClue: 4 },
    ],
  },
  {
    id: "coffee",
    answer: "Coffee",
    answerCanonical: "coffee",
    answerAliases: [],
    category: "Food & Drink",
    difficulty: "easy",
    clues: [
      { position: 1, text: "Legend credits its discovery to an Ethiopian goatherd who saw his flock dancing after nibbling certain red berries." },
      { position: 2, text: "One of the most heavily traded commodities on Earth, its 'beans' are really the roasted seeds of a fruit." },
      { position: 3, text: "Once banned in several places for its stimulating kick, it is pulled into espresso, cappuccino, and latte." },
      { position: 4, text: "This caffeinated morning brew, made from roasted ground beans, comes in Arabica and Robusta types." },
    ],
    decoys: [
      { text: "Tea", eliminatedByClue: 4 },
      { text: "Cocoa", eliminatedByClue: 3 },
    ],
  },
  {
    id: "chocolate",
    answer: "Chocolate",
    answerCanonical: "chocolate",
    answerAliases: [],
    category: "Food & Drink",
    difficulty: "easy",
    clues: [
      { position: 1, text: "The ancient Maya and Aztecs drank it bitter and spiced, and even used its beans as money." },
      { position: 2, text: "Pressed from the fermented, roasted seeds of a tropical tree, it melts at just below human body temperature." },
      { position: 3, text: "Poisonous to dogs thanks to a compound called theobromine, it is sold in dark, milk, and white forms." },
      { position: 4, text: "This sweet treat, made from cacao, fills Easter eggs and Valentine's boxes." },
    ],
    decoys: [
      { text: "Coffee", eliminatedByClue: 2 },
      { text: "Vanilla", eliminatedByClue: 4 },
    ],
  },
  {
    id: "the-beatles",
    answer: "The Beatles",
    answerCanonical: "the beatles",
    answerAliases: ["Beatles", "the Fab Four", "Fab Four"],
    category: "Music",
    difficulty: "easy",
    clues: [
      { position: 1, text: "A record label turned them down in 1962, declaring that guitar groups were 'on the way out.'" },
      { position: 2, text: "This four-piece from a northern English port city still holds the record for the most number-one hits on the U.S. charts." },
      { position: 3, text: "Made up of John, Paul, George, and Ringo, they quit touring in 1966 to pour themselves into studio albums like 'Sgt. Pepper.'" },
      { position: 4, text: "This Liverpool rock band of the 1960s recorded 'Hey Jude' and 'Let It Be.'" },
    ],
    decoys: [
      { text: "The Rolling Stones", eliminatedByClue: 3 },
      { text: "The Beach Boys", eliminatedByClue: 4 },
    ],
  },
  {
    id: "beethoven",
    answer: "Ludwig van Beethoven",
    answerCanonical: "ludwig van beethoven",
    answerAliases: ["Beethoven"],
    category: "Music",
    difficulty: "medium",
    clues: [
      { position: 1, text: "He wrote some of his greatest music, including his final symphony, while almost completely deaf." },
      { position: 2, text: "This German composer sawed the legs off his piano so he could feel its vibrations through the floor as his hearing failed." },
      { position: 3, text: "A bridge from the Classical to the Romantic era, his Fifth Symphony opens with four of the most famous notes in music: da-da-da-DUM." },
      { position: 4, text: "This wild-haired composer's Ninth Symphony gave the world the 'Ode to Joy.'" },
    ],
    decoys: [
      { text: "Wolfgang Amadeus Mozart", eliminatedByClue: 2 },
      { text: "Johann Sebastian Bach", eliminatedByClue: 4 },
    ],
  },
  {
    id: "chess",
    answer: "Chess",
    answerCanonical: "chess",
    answerAliases: [],
    category: "Games",
    difficulty: "medium",
    clues: [
      { position: 1, text: "The number of possible games it allows outstrips the count of atoms in the observable universe." },
      { position: 2, text: "Descended from the Indian game 'chaturanga' some 1,500 years ago, its most powerful piece was once feeble until European players supercharged her." },
      { position: 3, text: "Fought over 64 light and dark squares, its goal is to trap the enemy king in 'checkmate.'" },
      { position: 4, text: "In this two-player strategy game, each side marshals pawns, knights, bishops, rooks, a queen, and a king." },
    ],
    decoys: [
      { text: "Checkers", eliminatedByClue: 4 },
      { text: "Go", eliminatedByClue: 3 },
    ],
  },
  {
    id: "tokyo",
    answer: "Tokyo",
    answerCanonical: "tokyo",
    answerAliases: [],
    category: "Cities",
    difficulty: "easy",
    clues: [
      { position: 1, text: "As many as 3,000 people flood across its busiest pedestrian scramble every time the light turns." },
      { position: 2, text: "Once a fishing village called Edo, it grew into one of the world's biggest cities by the 1700s; its modern name means 'eastern capital.'" },
      { position: 3, text: "The most populous metropolitan area on the planet, it hosted the Summer Olympics in 1964 and again in 2021." },
      { position: 4, text: "This bustling Japanese capital is home to the Shibuya crossing and the Emperor's Imperial Palace." },
    ],
    decoys: [
      { text: "Kyoto", eliminatedByClue: 2 },
      { text: "Osaka", eliminatedByClue: 4 },
    ],
  },
  {
    id: "blue-whale",
    answer: "Blue Whale",
    answerCanonical: "blue whale",
    answerAliases: [],
    category: "Animals",
    difficulty: "easy",
    clues: [
      { position: 1, text: "A nursing newborn packs on roughly the weight of an adult human every single day." },
      { position: 2, text: "Its heart alone is about the size of a small car, and its low moans are the loudest sounds made by any animal." },
      { position: 3, text: "For all its bulk, it lives almost entirely on tiny shrimp-like krill, straining tons of them through fringed plates of baleen." },
      { position: 4, text: "The largest animal ever known to have lived, this baleen whale is named for its bluish-gray color." },
    ],
    decoys: [
      { text: "Sperm Whale", eliminatedByClue: 3 },
      { text: "Whale Shark", eliminatedByClue: 4 },
    ],
  },
  {
    id: "great-white-shark",
    answer: "Great White Shark",
    answerCanonical: "great white shark",
    answerAliases: ["great white"],
    category: "Animals",
    difficulty: "medium",
    clues: [
      { position: 1, text: "Jelly-filled pores on its snout let it sense the faint electric fields of a heartbeat, sniffing out prey hidden in the sand." },
      { position: 2, text: "Warmer-bodied than most fish, it can rocket its whole body clear out of the water to ambush a seal from below." },
      { position: 3, text: "It grows and sheds thousands of serrated teeth over its life, set in replaceable rows, yet has never survived long in a tank." },
      { position: 4, text: "The huge predatory fish behind the movie 'Jaws,' it is named for its pale underside." },
    ],
    decoys: [
      { text: "Killer Whale", eliminatedByClue: 4 },
      { text: "Tiger Shark", eliminatedByClue: 4 },
    ],
  },
  {
    id: "napoleon-bonaparte",
    answer: "Napoleon Bonaparte",
    answerCanonical: "napoleon bonaparte",
    answerAliases: ["Napoleon"],
    category: "History",
    difficulty: "medium",
    clues: [
      { position: 1, text: "The legend that he was unusually short is a myth — a muddle of old French and British units, sharpened by enemy cartoonists." },
      { position: 2, text: "Born on the island of Corsica, he rode the chaos of a revolution all the way to crowning himself emperor in 1804." },
      { position: 3, text: "His sweeping legal code still shapes law around the world, but his empire cracked after a catastrophic invasion of Russia." },
      { position: 4, text: "This French military genius met his final defeat at Waterloo in 1815 and died in exile on St. Helena." },
    ],
    decoys: [
      { text: "Julius Caesar", eliminatedByClue: 4 },
      { text: "Louis XVI", eliminatedByClue: 2 },
    ],
  },
  {
    id: "mount-fuji",
    answer: "Mount Fuji",
    answerCanonical: "mount fuji",
    answerAliases: ["Fuji", "Fujisan"],
    category: "Geography",
    difficulty: "medium",
    clues: [
      { position: 1, text: "Hokusai gave it an entire series of woodblock prints, among them one of a towering, claw-like wave." },
      { position: 2, text: "An active volcano that last erupted in 1707, its near-perfect symmetrical cone is a sacred site that draws hundreds of thousands of climbers each summer." },
      { position: 3, text: "The highest peak in its country at about 3,776 meters, it can be seen from Tokyo on a clear day." },
      { position: 4, text: "This snow-capped volcano is Japan's most famous mountain and a national symbol." },
    ],
    decoys: [
      { text: "Mount Kilimanjaro", eliminatedByClue: 3 },
      { text: "Mount Vesuvius", eliminatedByClue: 3 },
    ],
  },
  {
    id: "machu-picchu",
    answer: "Machu Picchu",
    answerCanonical: "machu picchu",
    answerAliases: ["the Lost City of the Incas"],
    category: "Landmarks",
    difficulty: "medium",
    clues: [
      { position: 1, text: "Its finest stones are cut and fitted so tightly, without any mortar, that a knife blade cannot slip between them." },
      { position: 2, text: "Built around 1450 and abandoned barely a century later, it slipped past the Spanish conquistadors entirely." },
      { position: 3, text: "Perched on a ridge high in the Peruvian Andes, it was brought to the world's attention by explorer Hiram Bingham in 1911." },
      { position: 4, text: "This mist-wrapped stone citadel is the most famous ruin of the Inca Empire." },
    ],
    decoys: [
      { text: "Chichen Itza", eliminatedByClue: 4 },
      { text: "Petra", eliminatedByClue: 3 },
    ],
  },
  {
    id: "the-nile",
    answer: "The Nile",
    answerCanonical: "the nile",
    answerAliases: ["Nile", "Nile River"],
    category: "Geography",
    difficulty: "medium",
    clues: [
      { position: 1, text: "Unlike most great rivers, it runs from south to north, emptying into the Mediterranean Sea." },
      { position: 2, text: "Its yearly floods laid down rich black silt that fed one of the world's earliest civilizations." },
      { position: 3, text: "Its two main branches, the White and the Blue, join at Khartoum in Sudan before the water flows on through Egypt." },
      { position: 4, text: "Often called the longest river on Earth, this African waterway was the lifeblood of ancient Egypt." },
    ],
    decoys: [
      { text: "Amazon River", eliminatedByClue: 1 },
      { text: "Congo River", eliminatedByClue: 3 },
    ],
  },
  {
    id: "charles-darwin",
    answer: "Charles Darwin",
    answerCanonical: "charles darwin",
    answerAliases: ["Darwin"],
    category: "Science",
    difficulty: "medium",
    clues: [
      { position: 1, text: "He sat on his world-changing theory for some twenty years before he dared to publish it." },
      { position: 2, text: "A five-year voyage aboard HMS Beagle — and especially the finches of the Galápagos Islands — reshaped his thinking." },
      { position: 3, text: "This English naturalist argued that living things change over generations through a process he called 'natural selection.'" },
      { position: 4, text: "His 1859 book 'On the Origin of Species' laid out the theory of evolution." },
    ],
    decoys: [
      { text: "Alfred Russel Wallace", eliminatedByClue: 4 },
      { text: "Gregor Mendel", eliminatedByClue: 2 },
    ],
  },
  {
    id: "amelia-earhart",
    answer: "Amelia Earhart",
    answerCanonical: "amelia earhart",
    answerAliases: ["Earhart"],
    category: "History",
    difficulty: "medium",
    clues: [
      { position: 1, text: "She vanished without a trace over the Pacific in 1937, and her fate is still argued about today." },
      { position: 2, text: "Five years earlier, in 1932, she became the first woman to fly solo across the Atlantic Ocean." },
      { position: 3, text: "She disappeared while trying to circle the globe, her plane lost somewhere near tiny Howland Island." },
      { position: 4, text: "This pioneering American aviator remains one of history's most famous missing persons." },
    ],
    decoys: [
      { text: "Charles Lindbergh", eliminatedByClue: 2 },
      { text: "Bessie Coleman", eliminatedByClue: 3 },
    ],
  },
  {
    id: "pizza",
    answer: "Pizza",
    answerCanonical: "pizza",
    answerAliases: [],
    category: "Food & Drink",
    difficulty: "easy",
    clues: [
      { position: 1, text: "Its classic Margherita version was supposedly dreamed up to honor an Italian queen, its red, white, and green echoing the flag." },
      { position: 2, text: "Born among the poor of Naples, it was long a humble street food before it conquered the world." },
      { position: 3, text: "The 'Hawaiian' style, crowned with pineapple, was actually invented in Canada in 1962." },
      { position: 4, text: "This round, oven-baked Italian dish of dough, tomato sauce, and cheese is served in wedges." },
    ],
    decoys: [
      { text: "Focaccia", eliminatedByClue: 3 },
      { text: "Calzone", eliminatedByClue: 4 },
    ],
  },
  {
    id: "basketball",
    answer: "Basketball",
    answerCanonical: "basketball",
    answerAliases: [],
    category: "Sports",
    difficulty: "easy",
    clues: [
      { position: 1, text: "The very first version used a fruit basket with its bottom still in, so someone had to fetch the ball by ladder after every score." },
      { position: 2, text: "Dr. James Naismith invented it in 1891 at a Massachusetts YMCA to keep students active indoors through the winter." },
      { position: 3, text: "Two teams bounce the ball as they move it, aiming to drop it through a hoop set 10 feet above the floor." },
      { position: 4, text: "In this sport, players 'dribble' and 'dunk' to score, and the NBA is its top professional league." },
    ],
    decoys: [
      { text: "Volleyball", eliminatedByClue: 3 },
      { text: "Netball", eliminatedByClue: 4 },
    ],
  },
  {
    id: "dolphin",
    answer: "Dolphin",
    answerCanonical: "dolphin",
    answerAliases: ["dolphins"],
    category: "Animals",
    difficulty: "easy",
    clues: [
      { position: 1, text: "It sleeps with only half its brain at a time, keeping one eye open so it never forgets to surface for air." },
      { position: 2, text: "It 'sees' with sound, firing rapid clicks and reading the echoes to map objects in murky water." },
      { position: 3, text: "Highly social and playful, each individual has its own signature whistle that works much like a name." },
      { position: 4, text: "This sleek, intelligent marine mammal, often seen leaping in a ship's wake, is a small toothed cousin of the whale." },
    ],
    decoys: [
      { text: "Porpoise", eliminatedByClue: 3 },
      { text: "Shark", eliminatedByClue: 4 },
    ],
  },
  {
    id: "owl",
    answer: "Owl",
    answerCanonical: "owl",
    answerAliases: ["owls"],
    category: "Animals",
    difficulty: "easy",
    clues: [
      { position: 1, text: "Its eyes are locked in their sockets, so it swivels its head as much as three-quarters of the way around to look about." },
      { position: 2, text: "Fringed feathers let it fly in near silence, and its hearing is sharp enough to seize prey in total darkness." },
      { position: 3, text: "A night hunter with a flat, disc-shaped face that funnels sound to its ears, it gulps small prey whole and coughs up the bones as pellets." },
      { position: 4, text: "This wide-eyed bird of prey, an age-old symbol of wisdom, is known for its haunting hoot." },
    ],
    decoys: [
      { text: "Hawk", eliminatedByClue: 2 },
      { text: "Bat", eliminatedByClue: 4 },
    ],
  },
  {
    id: "sloth",
    answer: "Sloth",
    answerCanonical: "sloth",
    answerAliases: ["sloths"],
    category: "Animals",
    difficulty: "medium",
    clues: [
      { position: 1, text: "It moves so little that green algae grows in its fur, tinting it mossy — handy camouflage in the canopy." },
      { position: 2, text: "Its digestion is so slow that a single leafy meal can take weeks to break down." },
      { position: 3, text: "It climbs down from the treetops only about once a week — to relieve itself — and can hold its breath longer than a dolphin." },
      { position: 4, text: "This famously slow-moving Central and South American mammal dangles upside down from branches by long, curved claws." },
    ],
    decoys: [
      { text: "Koala", eliminatedByClue: 3 },
      { text: "Anteater", eliminatedByClue: 4 },
    ],
  },
  {
    id: "lion",
    answer: "Lion",
    answerCanonical: "lion",
    answerAliases: ["lions"],
    category: "Animals",
    difficulty: "easy",
    clues: [
      { position: 1, text: "Its roar can carry as far as five miles, and among these cats it is usually the females who do the hunting." },
      { position: 2, text: "The one truly social member of its cat family, it lives in groups called prides and can doze for up to 20 hours a day." },
      { position: 3, text: "Males are set apart by a thick, shaggy mane, and the species once roamed across Africa, Europe, and Asia." },
      { position: 4, text: "Nicknamed 'king of the jungle,' this big tawny African cat is a byword for courage and royalty." },
    ],
    decoys: [
      { text: "Tiger", eliminatedByClue: 2 },
      { text: "Cheetah", eliminatedByClue: 3 },
    ],
  },
  {
    id: "gold",
    answer: "Gold",
    answerCanonical: "gold",
    answerAliases: [],
    category: "Science",
    difficulty: "easy",
    clues: [
      { position: 1, text: "Nearly all of it ever mined would fit inside just a few Olympic swimming pools, and much of it was forged in colliding neutron stars." },
      { position: 2, text: "So soft and unreactive that it never rusts or tarnishes, a single ounce can be beaten into a sheet covering a hundred square feet." },
      { position: 3, text: "Treasured for thousands of years, it carries the chemical symbol Au and is measured in carats for purity." },
      { position: 4, text: "This dense, shiny yellow precious metal fills central-bank vaults and hangs around the necks of Olympic champions." },
    ],
    decoys: [
      { text: "Silver", eliminatedByClue: 2 },
      { text: "Platinum", eliminatedByClue: 4 },
    ],
  },
  {
    id: "lightning",
    answer: "Lightning",
    answerCanonical: "lightning",
    answerAliases: [],
    category: "Science",
    difficulty: "easy",
    clues: [
      { position: 1, text: "For a split second it heats the surrounding air to roughly five times the temperature of the Sun's surface." },
      { position: 2, text: "The thunderclap you hear is simply the boom of air blasting outward from its superheated channel." },
      { position: 3, text: "It hits the Earth millions of times a day, and the Empire State Building is struck dozens of times a year." },
      { position: 4, text: "This sudden flash of electricity between cloud and ground rips across the sky during a thunderstorm." },
    ],
    decoys: [
      { text: "Thunder", eliminatedByClue: 2 },
      { text: "Aurora", eliminatedByClue: 3 },
    ],
  },
  {
    id: "dead-sea",
    answer: "Dead Sea",
    answerCanonical: "dead sea",
    answerAliases: ["the Dead Sea"],
    category: "Geography",
    difficulty: "medium",
    clues: [
      { position: 1, text: "It is so laden with salt that swimmers bob on the surface like corks, unable to sink." },
      { position: 2, text: "Its shores are the lowest dry land on Earth, more than 400 meters below sea level, and they creep lower every year as it shrinks." },
      { position: 3, text: "Nearly ten times saltier than the ocean, its harsh waters hold no fish or seaweed at all — which is how it got its name." },
      { position: 4, text: "This landlocked salt lake between Jordan and Israel is famous for mineral-rich mud and effortless floating." },
    ],
    decoys: [
      { text: "Great Salt Lake", eliminatedByClue: 4 },
      { text: "Caspian Sea", eliminatedByClue: 3 },
    ],
  },
  {
    id: "venice",
    answer: "Venice",
    answerCanonical: "venice",
    answerAliases: [],
    category: "Cities",
    difficulty: "medium",
    clues: [
      { position: 1, text: "It rests atop millions of wooden posts driven into the mud of a lagoon, and it has no ordinary streets for cars." },
      { position: 2, text: "Slowly sinking and prone to floods locals call 'acqua alta,' this Italian city gets around by boat along its waterways." },
      { position: 3, text: "Its Grand Canal, gondolas, and St. Mark's Square draw such crowds that the city now charges day-trippers to enter." },
      { position: 4, text: "This romantic northern Italian city of canals once commanded a powerful seafaring trading empire." },
    ],
    decoys: [
      { text: "Amsterdam", eliminatedByClue: 2 },
      { text: "Florence", eliminatedByClue: 1 },
    ],
  },
  {
    id: "paris",
    answer: "Paris",
    answerCanonical: "paris",
    answerAliases: [],
    category: "Cities",
    difficulty: "easy",
    clues: [
      { position: 1, text: "Beneath its streets wind tunnels stacked with the bones of some six million people, a vast underground ossuary." },
      { position: 2, text: "It is said to have just one stop sign in the whole city, and its residents stroll grand boulevards laid out in the 1800s." },
      { position: 3, text: "Home to the Louvre and the Notre-Dame cathedral, it is split by a river into a Left Bank and a Right Bank." },
      { position: 4, text: "This French capital, nicknamed the 'City of Light,' is famed for cafés, fashion, and a certain iron tower." },
    ],
    decoys: [
      { text: "London", eliminatedByClue: 4 },
      { text: "Rome", eliminatedByClue: 3 },
    ],
  },
  {
    id: "stonehenge",
    answer: "Stonehenge",
    answerCanonical: "stonehenge",
    answerAliases: [],
    category: "Landmarks",
    difficulty: "medium",
    clues: [
      { position: 1, text: "Some of its stones were dragged roughly 150 miles from the hills of Wales, though no one is certain how." },
      { position: 2, text: "Put up around 5,000 years ago, its great stones line up with the sunrise on the longest day of the year." },
      { position: 3, text: "Standing on Salisbury Plain in southern England, this ring of towering rocks left behind no written records to explain it." },
      { position: 4, text: "This prehistoric circle of massive standing stones is one of the world's most famous ancient monuments." },
    ],
    decoys: [
      { text: "Easter Island", eliminatedByClue: 3 },
      { text: "Newgrange", eliminatedByClue: 3 },
    ],
  },
  {
    id: "great-pyramid-of-giza",
    answer: "Great Pyramid of Giza",
    answerCanonical: "great pyramid of giza",
    answerAliases: ["the Great Pyramid", "Great Pyramid", "Pyramid of Khufu"],
    category: "Landmarks",
    difficulty: "medium",
    clues: [
      { position: 1, text: "For nearly 4,000 years it reigned as the tallest structure ever raised by human hands." },
      { position: 2, text: "The only one of the seven wonders of the ancient world still standing, it was built from over two million blocks of stone." },
      { position: 3, text: "Raised as a tomb for a pharaoh around 4,500 years ago, it looms over a desert plateau just outside Cairo, Egypt." },
      { position: 4, text: "This colossal ancient Egyptian monument at Giza, tomb of the pharaoh Khufu, is the largest structure of its kind." },
    ],
    decoys: [
      { text: "The Sphinx", eliminatedByClue: 4 },
      { text: "Colosseum", eliminatedByClue: 3 },
    ],
  },
  {
    id: "sydney-opera-house",
    answer: "Sydney Opera House",
    answerCanonical: "sydney opera house",
    answerAliases: ["the Sydney Opera House"],
    category: "Landmarks",
    difficulty: "medium",
    clues: [
      { position: 1, text: "Its architect quit the project in a bitter feud and never once saw the finished building in person." },
      { position: 2, text: "Paid for largely by a public lottery, it ran about 13 times over budget and took 14 years to complete." },
      { position: 3, text: "Its roof of gleaming white shells, often likened to billowing sails, rises beside a famous harbor in Australia." },
      { position: 4, text: "This sail-roofed performing-arts centre on Sydney Harbour is Australia's most recognizable building." },
    ],
    decoys: [
      { text: "Sydney Harbour Bridge", eliminatedByClue: 4 },
      { text: "Guggenheim Museum Bilbao", eliminatedByClue: 3 },
    ],
  },
  {
    id: "marie-antoinette",
    answer: "Marie Antoinette",
    answerCanonical: "marie antoinette",
    answerAliases: [],
    category: "History",
    difficulty: "medium",
    clues: [
      { position: 1, text: "She almost certainly never said 'let them eat cake' — the line was already circulating before she reached the throne." },
      { position: 2, text: "An Austrian archduchess married off to a French king as a teenager, she became a lightning rod for public fury." },
      { position: 3, text: "She was mocked for extravagant gowns, towering powdered wigs, and lavish spending as revolution simmered around her." },
      { position: 4, text: "This last queen of France before the revolution was sent to the guillotine in 1793." },
    ],
    decoys: [
      { text: "Catherine the Great", eliminatedByClue: 2 },
      { text: "Joan of Arc", eliminatedByClue: 4 },
    ],
  },
  {
    id: "abraham-lincoln",
    answer: "Abraham Lincoln",
    answerCanonical: "abraham lincoln",
    answerAliases: ["Lincoln", "Abe Lincoln"],
    category: "History",
    difficulty: "medium",
    clues: [
      { position: 1, text: "On the very day he was shot, he had signed the law creating the Secret Service — an agency first meant to chase counterfeiters, not guard presidents." },
      { position: 2, text: "A skilled wrestler in his youth and, at 6 foot 4, the tallest ever to hold his office, he had almost no formal schooling." },
      { position: 3, text: "He steered his nation through a civil war and issued the proclamation that began freeing enslaved people." },
      { position: 4, text: "This bearded 16th U.S. president, honored on the penny and the five-dollar bill, was assassinated in 1865." },
    ],
    decoys: [
      { text: "George Washington", eliminatedByClue: 2 },
      { text: "John F. Kennedy", eliminatedByClue: 4 },
    ],
  },
  {
    id: "wright-brothers",
    answer: "The Wright Brothers",
    answerCanonical: "the wright brothers",
    answerAliases: ["Wright Brothers", "the Wrights"],
    category: "History",
    difficulty: "medium",
    clues: [
      { position: 1, text: "They ran a modest bicycle shop before cracking a problem that had defeated inventors for centuries." },
      { position: 2, text: "Their breakthrough was less the engine than a way to twist a wing's shape to steer and hold balance in the air." },
      { position: 3, text: "On a windy North Carolina beach in 1903, their first powered flight lasted about 12 seconds and covered 120 feet." },
      { position: 4, text: "These two American brothers, Wilbur and Orville, built and flew the world's first successful airplane." },
    ],
    decoys: [
      { text: "Leonardo da Vinci", eliminatedByClue: 3 },
      { text: "Charles Lindbergh", eliminatedByClue: 4 },
    ],
  },
  {
    id: "cheetah",
    answer: "Cheetah",
    answerCanonical: "cheetah",
    answerAliases: ["cheetahs"],
    category: "Animals",
    difficulty: "easy",
    clues: [
      { position: 1, text: "It can out-accelerate most supercars from a standstill, yet it cannot roar — it chirps and purrs instead." },
      { position: 2, text: "Unlike other big cats, its claws never fully retract, giving it running spikes for grip at full tilt." },
      { position: 3, text: "The fastest land animal, it can hit around 70 mph in short bursts before it overheats and has to rest." },
      { position: 4, text: "This spotted African cat, marked by black 'tear' lines running down from its eyes, is built entirely for the sprint." },
    ],
    decoys: [
      { text: "Lion", eliminatedByClue: 1 },
      { text: "Leopard", eliminatedByClue: 2 },
    ],
  },
  {
    id: "platypus",
    answer: "Platypus",
    answerCanonical: "platypus",
    answerAliases: ["platypuses"],
    category: "Animals",
    difficulty: "medium",
    clues: [
      { position: 1, text: "It is one of the only mammals that lays eggs, and the males carry venom in a spur on each hind leg." },
      { position: 2, text: "It hunts with eyes, ears, and nose all sealed shut, sensing the faint electric fields of prey through its rubbery bill." },
      { position: 3, text: "Native to Australia, it has no stomach and no teeth, mashing food with bits of gravel it scoops up while feeding." },
      { position: 4, text: "This duck-billed, beaver-tailed, web-footed oddity so baffled naturalists that the first specimen was dismissed as a hoax." },
    ],
    decoys: [
      { text: "Otter", eliminatedByClue: 1 },
      { text: "Echidna", eliminatedByClue: 4 },
    ],
  },
  {
    id: "giraffe",
    answer: "Giraffe",
    answerCanonical: "giraffe",
    answerAliases: ["giraffes"],
    category: "Animals",
    difficulty: "easy",
    clues: [
      { position: 1, text: "For all that towering neck, it has exactly the same number of neck bones as you do — seven." },
      { position: 2, text: "Its tongue is nearly half a meter long and a dark blue-purple, a color thought to guard against sunburn while it feeds." },
      { position: 3, text: "The tallest animal on Earth, it survives on as little as 30 minutes of sleep a day and needs an outsized heart to pump blood up to its brain." },
      { position: 4, text: "This spotted African browser reaches leaves high in acacia trees that nothing else can touch." },
    ],
    decoys: [
      { text: "Ostrich", eliminatedByClue: 1 },
      { text: "Camel", eliminatedByClue: 4 },
    ],
  },
  {
    id: "pluto",
    answer: "Pluto",
    answerCanonical: "pluto",
    answerAliases: [],
    category: "Space",
    difficulty: "easy",
    clues: [
      { position: 1, text: "Once counted as the ninth planet, it was stripped of that title and reclassified as a 'dwarf' in 2006." },
      { position: 2, text: "Smaller even than Earth's own Moon, it takes about 248 Earth years to loop around the Sun just once." },
      { position: 3, text: "A 2015 flyby beamed back photos of a vast heart-shaped glacier of frozen nitrogen on its surface." },
      { position: 4, text: "This icy dwarf planet at the edge of the Solar System was discovered in 1930 and named by an 11-year-old girl." },
    ],
    decoys: [
      { text: "Neptune", eliminatedByClue: 1 },
      { text: "Eris", eliminatedByClue: 4 },
    ],
  },
  {
    id: "oxygen",
    answer: "Oxygen",
    answerCanonical: "oxygen",
    answerAliases: [],
    category: "Science",
    difficulty: "medium",
    clues: [
      { position: 1, text: "In liquid form it is a pale sky-blue and, oddly, is drawn toward a magnet." },
      { position: 2, text: "It makes up about a fifth of the air you breathe and roughly half of the Earth's crust by weight." },
      { position: 3, text: "With the chemical symbol O and atomic number 8, it is released by plants and required for any fire to burn." },
      { position: 4, text: "This colorless gas, essential to breathing, joins with hydrogen to form water." },
    ],
    decoys: [
      { text: "Nitrogen", eliminatedByClue: 2 },
      { text: "Hydrogen", eliminatedByClue: 4 },
    ],
  },
  {
    id: "rainbow",
    answer: "Rainbow",
    answerCanonical: "rainbow",
    answerAliases: [],
    category: "Science",
    difficulty: "easy",
    clues: [
      { position: 1, text: "It is really a full circle of light — from the ground you only ever glimpse the top arc." },
      { position: 2, text: "No two people see exactly the same one, since it depends on where the light happens to meet your own eyes." },
      { position: 3, text: "It appears when sunlight is bent and split inside countless tiny droplets, fanning white light into its bands." },
      { position: 4, text: "This arc of red-through-violet colors stretches across the sky when the sun shines during or after rain." },
    ],
    decoys: [
      { text: "Aurora", eliminatedByClue: 3 },
      { text: "Prism", eliminatedByClue: 4 },
    ],
  },
  {
    id: "volcano",
    answer: "Volcano",
    answerCanonical: "volcano",
    answerAliases: [],
    category: "Science",
    difficulty: "easy",
    clues: [
      { position: 1, text: "Its name comes from Vulcan, the Roman god of fire and the forge." },
      { position: 2, text: "About three-quarters of the world's active ones ring the Pacific in a belt nicknamed the 'Ring of Fire.'" },
      { position: 3, text: "As pressure builds below, it can erupt in rivers of molten lava, towering ash clouds, and choking gas." },
      { position: 4, text: "This crater-topped mountain, like Vesuvius or Krakatoa, forms where molten rock breaks through the Earth's crust." },
    ],
    decoys: [
      { text: "Earthquake", eliminatedByClue: 1 },
      { text: "Geyser", eliminatedByClue: 3 },
    ],
  },
  {
    id: "iceland",
    answer: "Iceland",
    answerCanonical: "iceland",
    answerAliases: [],
    category: "Geography",
    difficulty: "medium",
    clues: [
      { position: 1, text: "It straddles two tectonic plates that are slowly drifting apart, so the country grows a little wider each year." },
      { position: 2, text: "Almost all of its heat and power come from underground steam and waterfalls, and it has essentially no mosquitoes." },
      { position: 3, text: "Nicknamed the 'land of fire and ice' for its glaciers and volcanoes, it hosts the world's oldest still-running parliament." },
      { position: 4, text: "This sparsely populated North Atlantic island nation, whose capital is Reykjavík, is a prime spot to catch the Northern Lights." },
    ],
    decoys: [
      { text: "Norway", eliminatedByClue: 1 },
      { text: "Greenland", eliminatedByClue: 4 },
    ],
  },
  {
    id: "mount-rushmore",
    answer: "Mount Rushmore",
    answerCanonical: "mount rushmore",
    answerAliases: ["Rushmore"],
    category: "Landmarks",
    difficulty: "medium",
    clues: [
      { position: 1, text: "The four faces were meant to be carved down to the waist, but the money ran out first." },
      { position: 2, text: "Blasted and drilled into a granite cliff over 14 years, each head stands about 60 feet tall." },
      { position: 3, text: "Set in the Black Hills of South Dakota, it portrays Washington, Jefferson, Roosevelt, and Lincoln." },
      { position: 4, text: "This colossal mountainside carving of four U.S. presidents is one of America's most recognizable monuments." },
    ],
    decoys: [
      { text: "Crazy Horse Memorial", eliminatedByClue: 3 },
      { text: "Stone Mountain", eliminatedByClue: 4 },
    ],
  },
  {
    id: "leaning-tower-of-pisa",
    answer: "Leaning Tower of Pisa",
    answerCanonical: "leaning tower of pisa",
    answerAliases: ["the Leaning Tower of Pisa", "Leaning Tower", "Tower of Pisa"],
    category: "Landmarks",
    difficulty: "easy",
    clues: [
      { position: 1, text: "It began tilting before it was even finished, because it was set on soft, marshy ground." },
      { position: 2, text: "Construction dragged on for nearly 200 years, and engineers only halted its slow topple in the 1990s." },
      { position: 3, text: "A freestanding white marble bell tower beside a cathedral in Italy, it draws crowds posing to 'hold it up.'" },
      { position: 4, text: "This famously tilted Italian bell tower gives the city of Pisa its worldwide fame." },
    ],
    decoys: [
      { text: "Eiffel Tower", eliminatedByClue: 3 },
      { text: "Big Ben", eliminatedByClue: 4 },
    ],
  },
  {
    id: "golden-gate-bridge",
    answer: "Golden Gate Bridge",
    answerCanonical: "golden gate bridge",
    answerAliases: ["the Golden Gate Bridge"],
    category: "Landmarks",
    difficulty: "medium",
    clues: [
      { position: 1, text: "Its famous color is officially 'International Orange' — it was never actually golden." },
      { position: 2, text: "Painting it never really stops: crews work year-round to hold back the salty ocean rust." },
      { position: 3, text: "When it opened in 1937 it was the longest suspension bridge in the world, spanning a fog-wrapped strait." },
      { position: 4, text: "This burnt-orange landmark links San Francisco to Marin County across the mouth of its bay." },
    ],
    decoys: [
      { text: "Bay Bridge", eliminatedByClue: 1 },
      { text: "Brooklyn Bridge", eliminatedByClue: 4 },
    ],
  },
  {
    id: "rome",
    answer: "Rome",
    answerCanonical: "rome",
    answerAliases: [],
    category: "Cities",
    difficulty: "easy",
    clues: [
      { position: 1, text: "It completely surrounds another country — the smallest in the world — inside its own city limits." },
      { position: 2, text: "Legend says twin brothers raised by a wolf founded it, and it was built across seven hills." },
      { position: 3, text: "Visitors toss around three thousand euros a day into its Trevi Fountain, and its ancient arena once staged gladiator fights." },
      { position: 4, text: "Nicknamed the 'Eternal City,' this Italian capital straddles the Tiber River." },
    ],
    decoys: [
      { text: "Florence", eliminatedByClue: 1 },
      { text: "Athens", eliminatedByClue: 4 },
    ],
  },
  {
    id: "london",
    answer: "London",
    answerCanonical: "london",
    answerAliases: [],
    category: "Cities",
    difficulty: "easy",
    clues: [
      { position: 1, text: "Its subway, the world's first, opened in 1863 — locals just call it 'the Tube.'" },
      { position: 2, text: "A great fire gutted it in 1666, and legend holds the kingdom will fall if the ravens ever abandon its ancient riverside fortress." },
      { position: 3, text: "Straddling the River Thames, it is dotted with red double-decker buses, black cabs, and a giant Ferris wheel called the Eye." },
      { position: 4, text: "This capital on the Thames is home to Buckingham Palace and the clock tower that houses Big Ben." },
    ],
    decoys: [
      { text: "Edinburgh", eliminatedByClue: 3 },
      { text: "Paris", eliminatedByClue: 4 },
    ],
  },
  {
    id: "sushi",
    answer: "Sushi",
    answerCanonical: "sushi",
    answerAliases: [],
    category: "Food & Drink",
    difficulty: "easy",
    clues: [
      { position: 1, text: "It began not as a delicacy but as a way to preserve fish, packed in fermented rice that was then thrown away." },
      { position: 2, text: "The name actually refers to the seasoned, vinegared rice — not to the raw fish many people assume it means." },
      { position: 3, text: "Often wrapped in sheets of dried seaweed and served with wasabi, pickled ginger, and soy sauce, it is eaten in bite-sized pieces." },
      { position: 4, text: "This Japanese dish of vinegared rice with fish or vegetables comes in forms like nigiri and maki rolls." },
    ],
    decoys: [
      { text: "Sashimi", eliminatedByClue: 2 },
      { text: "Ramen", eliminatedByClue: 3 },
    ],
  },
  {
    id: "genghis-khan",
    answer: "Genghis Khan",
    answerCanonical: "genghis khan",
    answerAliases: ["Chinggis Khan"],
    category: "History",
    difficulty: "medium",
    clues: [
      { position: 1, text: "A genetics study suggests roughly one in 200 men alive today may descend from him." },
      { position: 2, text: "Born with the name Temüjin, he welded the warring nomadic tribes of the steppe into a single force." },
      { position: 3, text: "He built the largest contiguous land empire in history, reaching from the Pacific coast toward Europe." },
      { position: 4, text: "This feared 13th-century Mongol conqueror was laid to rest in a secret grave that has never been found." },
    ],
    decoys: [
      { text: "Kublai Khan", eliminatedByClue: 2 },
      { text: "Attila the Hun", eliminatedByClue: 4 },
    ],
  },
  {
    id: "polar-bear",
    answer: "Polar Bear",
    answerCanonical: "polar bear",
    answerAliases: ["polar bears"],
    category: "Animals",
    difficulty: "easy",
    clues: [
      { position: 1, text: "Under its white-looking coat its skin is jet black, and each strand of fur is a hollow, see-through tube." },
      { position: 2, text: "A tireless swimmer, it can paddle for days across open Arctic sea and smell a seal from over a kilometer away." },
      { position: 3, text: "The largest land carnivore on Earth, it hunts seals from the sea ice and can fast for months between big meals." },
      { position: 4, text: "This great white bear of the far north is increasingly at risk as the sea ice it hunts on melts away." },
    ],
    decoys: [
      { text: "Arctic Fox", eliminatedByClue: 3 },
      { text: "Grizzly Bear", eliminatedByClue: 4 },
    ],
  },
  {
    id: "hummingbird",
    answer: "Hummingbird",
    answerCanonical: "hummingbird",
    answerAliases: ["hummingbirds"],
    category: "Animals",
    difficulty: "medium",
    clues: [
      { position: 1, text: "It is the only bird that can fly backward, and its heart can race past a thousand beats a minute." },
      { position: 2, text: "Its wings blur in a figure-eight up to 80 times a second, making the very sound it's named for." },
      { position: 3, text: "So hungry it must feed almost constantly, it laps nectar with a long tongue and drops into a deep, near-frozen sleep at night." },
      { position: 4, text: "This tiniest of birds, some barely larger than a bee, hovers at flowers on wings too fast to see." },
    ],
    decoys: [
      { text: "Sunbird", eliminatedByClue: 2 },
      { text: "Dragonfly", eliminatedByClue: 4 },
    ],
  },
  {
    id: "crocodile",
    answer: "Crocodile",
    answerCanonical: "crocodile",
    answerAliases: ["crocodiles"],
    category: "Animals",
    difficulty: "medium",
    clues: [
      { position: 1, text: "It has changed so little in 200 million years that it watched the dinosaurs come and go." },
      { position: 2, text: "Its bite is among the most powerful ever measured, yet the muscles that open its jaws are so weak a rubber band can hold them shut." },
      { position: 3, text: "A cold-blooded ambush hunter, it can go months without eating and lurks with only its eyes and nostrils above the water." },
      { position: 4, text: "This armored, long-snouted reptile is often mixed up with its close cousin the alligator." },
    ],
    decoys: [
      { text: "Komodo Dragon", eliminatedByClue: 2 },
      { text: "Alligator", eliminatedByClue: 4 },
    ],
  },
  {
    id: "flamingo",
    answer: "Flamingo",
    answerCanonical: "flamingo",
    answerAliases: ["flamingos", "flamingoes"],
    category: "Animals",
    difficulty: "easy",
    clues: [
      { position: 1, text: "It hatches out gray and turns pink only from the tiny shrimp and algae it eats." },
      { position: 2, text: "It will stand on a single stick-thin leg for hours, even asleep, and feeds with its head held upside down." },
      { position: 3, text: "These tall wading birds crowd onto salty lakes and lagoons in flocks thousands strong." },
      { position: 4, text: "This pink, long-necked bird is just as famous as a plastic lawn ornament." },
    ],
    decoys: [
      { text: "Heron", eliminatedByClue: 1 },
      { text: "Stork", eliminatedByClue: 4 },
    ],
  },
  {
    id: "wolf",
    answer: "Wolf",
    answerCanonical: "wolf",
    answerAliases: ["wolves", "gray wolf", "grey wolf"],
    category: "Animals",
    difficulty: "easy",
    clues: [
      { position: 1, text: "Every domestic dog, from chihuahua to Great Dane, descends from it." },
      { position: 2, text: "It lives and hunts in tight family packs led by a breeding pair, calling across miles with a mournful howl." },
      { position: 3, text: "The largest wild member of the dog family, it once ranged more widely than any land mammal except humans." },
      { position: 4, text: "This howling pack hunter is the ancestor of 'man's best friend' and the villain of many a fairy tale." },
    ],
    decoys: [
      { text: "Fox", eliminatedByClue: 2 },
      { text: "Coyote", eliminatedByClue: 3 },
    ],
  },
  {
    id: "snail",
    answer: "Snail",
    answerCanonical: "snail",
    answerAliases: ["snails"],
    category: "Animals",
    difficulty: "medium",
    clues: [
      { position: 1, text: "It glides on a single muscular foot, laying down slime that lets it crawl across a razor's edge unharmed." },
      { position: 2, text: "It carries its home on its back and can seal itself inside to sleep for months, even years, in dry spells." },
      { position: 3, text: "Its mouth holds thousands of microscopic teeth on a ribbon-like tongue, and many kinds are both male and female at once." },
      { position: 4, text: "This slow, shell-carrying mollusc leaves a shimmering trail and is a close cousin of the slug." },
    ],
    decoys: [
      { text: "Turtle", eliminatedByClue: 3 },
      { text: "Slug", eliminatedByClue: 4 },
    ],
  },
  {
    id: "bat",
    answer: "Bat",
    answerCanonical: "bat",
    answerAliases: ["bats"],
    category: "Animals",
    difficulty: "easy",
    clues: [
      { position: 1, text: "It is the only mammal capable of true, sustained flight." },
      { position: 2, text: "Many kinds find their way and their prey in pitch dark by shouting and reading the returning echoes." },
      { position: 3, text: "Hanging upside down in caves by day, some feast on insects, some on fruit, and a famous few on blood." },
      { position: 4, text: "This winged, night-flying mammal flits through the dark and inspired a certain caped superhero." },
    ],
    decoys: [
      { text: "Owl", eliminatedByClue: 1 },
      { text: "Flying Squirrel", eliminatedByClue: 2 },
    ],
  },
  {
    id: "frog",
    answer: "Frog",
    answerCanonical: "frog",
    answerAliases: ["frogs"],
    category: "Animals",
    difficulty: "easy",
    clues: [
      { position: 1, text: "It drinks and even breathes partly through its skin, so it has to stay damp to survive." },
      { position: 2, text: "It starts life as a swimming tadpole with gills and a tail, then remakes its whole body as it grows legs." },
      { position: 3, text: "Many kinds leap many times their own length, and some rainforest species ooze deadly poison through their vivid skin." },
      { position: 4, text: "This hopping amphibian croaks by night near ponds and snatches insects with a long, sticky tongue." },
    ],
    decoys: [
      { text: "Toad", eliminatedByClue: 1 },
      { text: "Salamander", eliminatedByClue: 3 },
    ],
  },
  {
    id: "mercury-planet",
    answer: "Mercury",
    answerCanonical: "mercury",
    answerAliases: [],
    category: "Space",
    difficulty: "medium",
    clues: [
      { position: 1, text: "A year here — one loop around the Sun — lasts only 88 Earth days, the shortest of any planet." },
      { position: 2, text: "Nearest to the Sun, it bakes by day but has almost no atmosphere to hold heat, so nights plunge far below freezing." },
      { position: 3, text: "Barely larger than Earth's Moon and covered in craters, it is the smallest planet in the Solar System." },
      { position: 4, text: "This swift innermost planet takes its name from the winged Roman messenger god." },
    ],
    decoys: [
      { text: "Venus", eliminatedByClue: 2 },
      { text: "Mars", eliminatedByClue: 3 },
    ],
  },
  {
    id: "neptune",
    answer: "Neptune",
    answerCanonical: "neptune",
    answerAliases: [],
    category: "Space",
    difficulty: "medium",
    clues: [
      { position: 1, text: "It was found not by looking but by arithmetic — its place predicted from odd wobbles in another planet's orbit." },
      { position: 2, text: "The windiest world in the Solar System, its storms shriek at over a thousand miles per hour." },
      { position: 3, text: "A deep-blue ice giant, it orbits so far out that a single one of its years lasts about 165 Earth years." },
      { position: 4, text: "The eighth and most distant planet from the Sun, it is named for the Roman god of the sea." },
    ],
    decoys: [
      { text: "Uranus", eliminatedByClue: 2 },
      { text: "Jupiter", eliminatedByClue: 3 },
    ],
  },
  {
    id: "halleys-comet",
    answer: "Halley's Comet",
    answerCanonical: "Halley's Comet",
    answerAliases: ["Halley", "Comet Halley"],
    category: "Space",
    difficulty: "medium",
    clues: [
      { position: 1, text: "Bright enough to see with the naked eye, it is the only such comet that can swing back within a single human lifetime — every 75 or 76 years." },
      { position: 2, text: "An English astronomer realized that several past sightings were one returning object and foretold its comeback, which arrived after his death." },
      { position: 3, text: "A dirty snowball of ice and dust, it last swept past Earth in 1986 and won't return until 2061." },
      { position: 4, text: "This most famous of comets carries the name of the man who predicted its return." },
    ],
    decoys: [
      { text: "Meteor", eliminatedByClue: 1 },
      { text: "Hale-Bopp", eliminatedByClue: 3 },
    ],
  },
  {
    id: "black-hole",
    answer: "Black Hole",
    answerCanonical: "black hole",
    answerAliases: ["black holes"],
    category: "Space",
    difficulty: "medium",
    clues: [
      { position: 1, text: "Its gravity is so ferocious that not even light can escape once it crosses the edge of no return." },
      { position: 2, text: "Time itself drags near it, and anything falling in would seem to freeze and redden at its boundary." },
      { position: 3, text: "Often born when a giant star collapses, the largest ones anchor the centers of galaxies, our own included." },
      { position: 4, text: "This invisible cosmic drain was first photographed in 2019 as a dark circle ringed by glowing gas." },
    ],
    decoys: [
      { text: "Supernova", eliminatedByClue: 1 },
      { text: "Neutron Star", eliminatedByClue: 4 },
    ],
  },
  {
    id: "water",
    answer: "Water",
    answerCanonical: "water",
    answerAliases: [],
    category: "Science",
    difficulty: "easy",
    clues: [
      { position: 1, text: "Almost uniquely, its solid form floats on its liquid — which is why ice forms on top of a pond, not the bottom." },
      { position: 2, text: "It is the only everyday substance found naturally on Earth as a solid, a liquid, and a gas." },
      { position: 3, text: "It blankets about 70% of the planet and most of your body; every molecule is two hydrogen atoms bound to one of oxygen." },
      { position: 4, text: "This clear, tasteless liquid, vital to all known life, falls as rain and fills the oceans." },
    ],
    decoys: [
      { text: "Air", eliminatedByClue: 1 },
      { text: "Ice", eliminatedByClue: 4 },
    ],
  },
  {
    id: "dna",
    answer: "DNA",
    answerCanonical: "dna",
    answerAliases: ["deoxyribonucleic acid"],
    category: "Science",
    difficulty: "medium",
    clues: [
      { position: 1, text: "Unwound, the copy inside just one of your cells would stretch about two meters, and all of yours together would reach the Sun and back many times over." },
      { position: 2, text: "It coils into a twisting 'double helix' ladder, a shape revealed in 1953." },
      { position: 3, text: "Spelled out in only four chemical letters — A, T, C, and G — it carries the instructions for building a living thing." },
      { position: 4, text: "This molecule, found in nearly every cell, holds the genetic code passed from parents to their children." },
    ],
    decoys: [
      { text: "RNA", eliminatedByClue: 2 },
      { text: "Protein", eliminatedByClue: 3 },
    ],
  },
  {
    id: "salt",
    answer: "Salt",
    answerCanonical: "salt",
    answerAliases: [],
    category: "Science",
    difficulty: "easy",
    clues: [
      { position: 1, text: "Roman soldiers were sometimes paid in it — which is where the word 'salary' comes from." },
      { position: 2, text: "Once so precious it traded ounce for ounce with gold, it was hauled across the Sahara in great caravans." },
      { position: 3, text: "It is a crystal of two elements — a metal that bursts into flame in water and a poisonous green gas — yet together they are harmless and essential." },
      { position: 4, text: "This white seasoning, shaken onto food the world over, is chemically sodium chloride." },
    ],
    decoys: [
      { text: "Sugar", eliminatedByClue: 3 },
      { text: "Pepper", eliminatedByClue: 4 },
    ],
  },
  {
    id: "electricity",
    answer: "Electricity",
    answerCanonical: "electricity",
    answerAliases: [],
    category: "Science",
    difficulty: "easy",
    clues: [
      { position: 1, text: "It races through a wire at nearly the speed of light, even though the particles that carry it barely crawl." },
      { position: 2, text: "The same force that snaps as a spark from your finger on a doorknob also splits the sky in a storm." },
      { position: 3, text: "Made by spinning magnets in power plants, it flows as a current of tiny charged particles called electrons." },
      { position: 4, text: "This form of energy lights our bulbs and runs our devices, measured in volts and amps." },
    ],
    decoys: [
      { text: "Magnetism", eliminatedByClue: 3 },
      { text: "Lightning", eliminatedByClue: 4 },
    ],
  },
  {
    id: "mount-kilimanjaro",
    answer: "Mount Kilimanjaro",
    answerCanonical: "mount kilimanjaro",
    answerAliases: ["Kilimanjaro"],
    category: "Geography",
    difficulty: "medium",
    clues: [
      { position: 1, text: "It is the tallest mountain on Earth that stands alone rather than in a range — a lone giant rising straight off the plains." },
      { position: 2, text: "Though it sits close to the equator, its summit wears glaciers and snow that are steadily melting away." },
      { position: 3, text: "Africa's highest peak, this dormant volcano in Tanzania can be walked to the top without ropes or climbing gear." },
      { position: 4, text: "This snow-capped Tanzanian volcano is the highest point on the whole African continent." },
    ],
    decoys: [
      { text: "Mount Everest", eliminatedByClue: 1 },
      { text: "Mount Fuji", eliminatedByClue: 4 },
    ],
  },
  {
    id: "amazon-rainforest",
    answer: "Amazon Rainforest",
    answerCanonical: "amazon rainforest",
    answerAliases: ["the Amazon", "Amazonia"],
    category: "Geography",
    difficulty: "easy",
    clues: [
      { position: 1, text: "It pumps out so much of the world's oxygen that it is often called the planet's 'lungs.'" },
      { position: 2, text: "One in ten known species on Earth lives here, many still unnamed, beneath a canopy so dense little light reaches the ground." },
      { position: 3, text: "Sprawling mostly across Brazil, this vast tropical jungle is drained by the largest river on Earth by volume." },
      { position: 4, text: "This immense South American rainforest, home to jaguars and poison dart frogs, is the biggest on the planet." },
    ],
    decoys: [
      { text: "The Congo", eliminatedByClue: 3 },
      { text: "Borneo", eliminatedByClue: 4 },
    ],
  },
  {
    id: "hawaii",
    answer: "Hawaii",
    answerCanonical: "hawaii",
    answerAliases: [],
    category: "Geography",
    difficulty: "easy",
    clues: [
      { position: 1, text: "Its largest island is still growing, as active volcanoes keep pouring out lava that hardens into new land." },
      { position: 2, text: "The most remote major island chain on Earth, it lies more than 2,000 miles from the nearest continent." },
      { position: 3, text: "The only U.S. state made entirely of islands — and the only one that grows coffee and was once its own kingdom." },
      { position: 4, text: "This tropical Pacific state, birthplace of surfing and the greeting 'aloha,' was the 50th to join the U.S." },
    ],
    decoys: [
      { text: "Alaska", eliminatedByClue: 3 },
      { text: "Fiji", eliminatedByClue: 4 },
    ],
  },
  {
    id: "big-ben",
    answer: "Big Ben",
    answerCanonical: "big ben",
    answerAliases: [],
    category: "Landmarks",
    difficulty: "easy",
    clues: [
      { position: 1, text: "Strictly, the name belongs to the giant bell inside, not the tower everyone points at." },
      { position: 2, text: "Its clock keeps famously precise time, fine-tuned by adding or removing old penny coins on the pendulum." },
      { position: 3, text: "Rising over the Houses of Parliament in London, its chimes are broadcast across Britain to mark the hour." },
      { position: 4, text: "This iconic clock tower beside the River Thames is one of London's most recognizable sights." },
    ],
    decoys: [
      { text: "Leaning Tower of Pisa", eliminatedByClue: 2 },
      { text: "Eiffel Tower", eliminatedByClue: 4 },
    ],
  },
  {
    id: "christ-the-redeemer",
    answer: "Christ the Redeemer",
    answerCanonical: "christ the redeemer",
    answerAliases: [],
    category: "Landmarks",
    difficulty: "medium",
    clues: [
      { position: 1, text: "Struck by lightning several times a year, it needs regular repairs to its head and outstretched hands." },
      { position: 2, text: "Its pieces were made in France and shipped across the ocean, then hauled up a steep peak above a huge bay." },
      { position: 3, text: "Arms spread nearly 30 meters wide, this Art Deco statue gazes over Rio de Janeiro from Corcovado mountain." },
      { position: 4, text: "This colossal mountaintop statue of Jesus is the great symbol of Brazil." },
    ],
    decoys: [
      { text: "Statue of Liberty", eliminatedByClue: 3 },
      { text: "Colossus of Rhodes", eliminatedByClue: 4 },
    ],
  },
  {
    id: "great-sphinx",
    answer: "Great Sphinx of Giza",
    answerCanonical: "great sphinx of giza",
    answerAliases: ["the Sphinx", "Great Sphinx", "Sphinx"],
    category: "Landmarks",
    difficulty: "medium",
    clues: [
      { position: 1, text: "It is missing its nose, and the popular tale that Napoleon's cannons blasted it off is almost certainly false." },
      { position: 2, text: "Carved from a single ridge of limestone some 4,500 years ago, it was once buried in sand up to its neck." },
      { position: 3, text: "This colossal statue with the body of a lion and the face of a human keeps watch over the pyramids outside Cairo." },
      { position: 4, text: "This giant ancient Egyptian monument, a reclining lion with a pharaoh's head, rests on the Giza plateau." },
    ],
    decoys: [
      { text: "Colossus of Rhodes", eliminatedByClue: 3 },
      { text: "The Great Pyramid", eliminatedByClue: 4 },
    ],
  },
  {
    id: "cairo",
    answer: "Cairo",
    answerCanonical: "cairo",
    answerAliases: [],
    category: "Cities",
    difficulty: "medium",
    clues: [
      { position: 1, text: "Its name means 'the Victorious,' and locals nickname it 'the City of a Thousand Minarets.'" },
      { position: 2, text: "The largest city in the Arab world, it is split by the same river that fed the pharaohs thousands of years ago." },
      { position: 3, text: "On its western edge rise the ancient pyramids of Giza; through its heart winds the Nile." },
      { position: 4, text: "This sprawling Egyptian capital is the biggest city in both Africa and the Middle East." },
    ],
    decoys: [
      { text: "Baghdad", eliminatedByClue: 3 },
      { text: "Alexandria", eliminatedByClue: 4 },
    ],
  },
  {
    id: "istanbul",
    answer: "Istanbul",
    answerCanonical: "istanbul",
    answerAliases: [],
    category: "Cities",
    difficulty: "medium",
    clues: [
      { position: 1, text: "It is the only major city in the world that straddles two continents at once." },
      { position: 2, text: "Once known as Byzantium and later Constantinople, it served as the capital of two great empires." },
      { position: 3, text: "A busy strait runs through it, dividing Europe from Asia, with bridges stitching the two halves together." },
      { position: 4, text: "This Turkish city on the Bosphorus, home to the Hagia Sophia and the Blue Mosque, is the nation's largest." },
    ],
    decoys: [
      { text: "Rome", eliminatedByClue: 1 },
      { text: "Athens", eliminatedByClue: 2 },
    ],
  },
  {
    id: "rio-de-janeiro",
    answer: "Rio de Janeiro",
    answerCanonical: "rio de janeiro",
    answerAliases: ["Rio"],
    category: "Cities",
    difficulty: "medium",
    clues: [
      { position: 1, text: "For a time it was the capital not only of its own country but of a whole European empire, whose king had fled there across the sea." },
      { position: 2, text: "Its vast Carnival, with samba parades and glittering costumes, is among the biggest street parties on Earth." },
      { position: 3, text: "Framed by the Sugarloaf peak and a giant hilltop statue of Christ, it wraps around a stunning Brazilian bay." },
      { position: 4, text: "This Brazilian city, famed for Copacabana beach and Carnival, hosted the 2016 Summer Olympics." },
    ],
    decoys: [
      { text: "Lisbon", eliminatedByClue: 3 },
      { text: "São Paulo", eliminatedByClue: 4 },
    ],
  },
  {
    id: "julius-caesar",
    answer: "Julius Caesar",
    answerCanonical: "julius caesar",
    answerAliases: ["Caesar"],
    category: "History",
    difficulty: "medium",
    clues: [
      { position: 1, text: "A calendar he introduced still orders our year, and the month of July is named in his honor." },
      { position: 2, text: "He famously led his army across a river called the Rubicon — a point of no return that touched off a civil war." },
      { position: 3, text: "This Roman general turned dictator was stabbed to death by senators on the Ides of March, 44 BC." },
      { position: 4, text: "Betrayed by his friend Brutus, this Roman ruler's dying words are remembered as 'Et tu, Brute?'" },
    ],
    decoys: [
      { text: "Augustus", eliminatedByClue: 1 },
      { text: "Mark Antony", eliminatedByClue: 3 },
    ],
  },
  {
    id: "christopher-columbus",
    answer: "Christopher Columbus",
    answerCanonical: "christopher columbus",
    answerAliases: ["Columbus"],
    category: "History",
    difficulty: "medium",
    clues: [
      { position: 1, text: "He reached the Americas insisting, to his dying day, that he had merely found a new sea route to Asia." },
      { position: 2, text: "Bankrolled by the Spanish crown in 1492, he sailed west with three ships — the Niña, the Pinta, and the Santa María." },
      { position: 3, text: "His voyages threw open the door to European colonization of the New World, for better and far worse." },
      { position: 4, text: "This Italian explorer's 1492 crossing is marked by a holiday and by a U.S. capital city named after him." },
    ],
    decoys: [
      { text: "Ferdinand Magellan", eliminatedByClue: 2 },
      { text: "Amerigo Vespucci", eliminatedByClue: 4 },
    ],
  },
  {
    id: "nikola-tesla",
    answer: "Nikola Tesla",
    answerCanonical: "nikola tesla",
    answerAliases: ["Tesla"],
    category: "History",
    difficulty: "medium",
    clues: [
      { position: 1, text: "He claimed to build machines entirely in his head, running them for weeks in his imagination before making a single part." },
      { position: 2, text: "A rival of Edison, he championed the alternating-current system that lights homes around the world today." },
      { position: 3, text: "This Serbian-American inventor dreamed of beaming electricity through the air and died nearly penniless despite his genius." },
      { position: 4, text: "A unit of magnetic strength and an electric-car company both carry this eccentric inventor's name." },
    ],
    decoys: [
      { text: "Thomas Edison", eliminatedByClue: 2 },
      { text: "Guglielmo Marconi", eliminatedByClue: 3 },
    ],
  },
  {
    id: "cheese",
    answer: "Cheese",
    answerCanonical: "cheese",
    answerAliases: [],
    category: "Food & Drink",
    difficulty: "easy",
    clues: [
      { position: 1, text: "Legend says it was discovered by accident, when milk carried in a pouch made from an animal's stomach curdled on a journey." },
      { position: 2, text: "Some prized kinds are laced on purpose with blue mold or left to age for years in cool caves." },
      { position: 3, text: "Made by curdling milk and draining off the watery whey, it comes in hundreds of styles from cheddar to brie." },
      { position: 4, text: "This dairy food, melted over pizza and paired with wine, is made from milk." },
    ],
    decoys: [
      { text: "Yogurt", eliminatedByClue: 2 },
      { text: "Butter", eliminatedByClue: 3 },
    ],
  },
  {
    id: "soccer",
    answer: "Soccer",
    answerCanonical: "soccer",
    answerAliases: ["football", "association football"],
    category: "Sports",
    difficulty: "easy",
    clues: [
      { position: 1, text: "Its championship final draws a television audience of billions — more than any other single sporting event on Earth." },
      { position: 2, text: "Apart from the goalkeeper, players may not touch the ball with their hands, moving it by foot, head, and chest." },
      { position: 3, text: "Played by two sides of eleven on a grass pitch, its World Cup is contested every four years." },
      { position: 4, text: "In this global game, fans roar as the ball is kicked into a net; Pelé and Messi are among its legends." },
    ],
    decoys: [
      { text: "Rugby", eliminatedByClue: 2 },
      { text: "American Football", eliminatedByClue: 4 },
    ],
  },
];
