/**
 * Expanded question bank — 40 hand-written questions added to grow the daily
 * and practice pools. Same shape and rules as the seed samples (spec §2.2):
 * every clue true of the answer; clues 1–2 also plausibly fit a decoy; each
 * later clue eliminates a decoy or adds recognizability; clue 4 is a fair
 * giveaway; no clue contains the answer or an obvious derivative.
 *
 * Style note: clue 1 is written crossword-terse — one oblique, surprising
 * fact rather than a descriptive paragraph — so a fast solver can leap on it
 * but a casual solver still needs the ladder. Clues 2–4 open up from there.
 *
 * These merge into the local bank after SEED_QUESTIONS and (when present) the
 * gitignored private bank. They are validated by the same integrity suite.
 */

import type { Question } from "@/lib/game/types";

export const EXTRA_QUESTIONS: Question[] = [
  {
    id: "saturn",
    answer: "Saturn",
    answerCanonical: "saturn",
    answerAliases: [],
    category: "Space",
    difficulty: "easy",
    clues: [
      { position: 1, text: "Less dense than water, it would float if you could find a bathtub big enough." },
      { position: 2, text: "It is not the only planet with rings, but its bright, icy bands are by far the widest and most spectacular in the Solar System." },
      { position: 3, text: "The sixth planet from the Sun, it takes about 29 Earth years to circle once and hosts a giant moon, Titan, with a thick orange atmosphere." },
      { position: 4, text: "This ringed gas giant lends its name to the day between Friday and Sunday." },
    ],
    decoys: [
      { text: "Jupiter", eliminatedByClue: 2 },
      { text: "Uranus", eliminatedByClue: 3 },
    ],
  },
  {
    id: "jupiter",
    answer: "Jupiter",
    answerCanonical: "jupiter",
    answerAliases: [],
    category: "Space",
    difficulty: "easy",
    clues: [
      { position: 1, text: "A single storm on it has raged for centuries and is wide enough to swallow the whole Earth." },
      { position: 2, text: "The largest planet in the Solar System, it is so massive that every other planet could fit inside it with room to spare." },
      { position: 3, text: "Galileo spotted its four biggest moons in 1610; one of them, Ganymede, is larger than the planet Mercury." },
      { position: 4, text: "The fifth planet from the Sun, this banded giant is named for the king of the Roman gods." },
    ],
    decoys: [
      { text: "Saturn", eliminatedByClue: 2 },
      { text: "Neptune", eliminatedByClue: 2 },
    ],
  },
  {
    id: "mars",
    answer: "Mars",
    answerCanonical: "mars",
    answerAliases: ["the Red Planet"],
    category: "Space",
    difficulty: "easy",
    clues: [
      { position: 1, text: "It boasts both the tallest volcano and one of the deepest canyons known anywhere in the Solar System." },
      { position: 2, text: "A cold desert world with a thin atmosphere, its rusty, iron-rich soil tints it a color you can spot with the naked eye." },
      { position: 3, text: "Two tiny lumpy moons, Phobos and Deimos, orbit it, and rovers named Curiosity and Perseverance roam its surface." },
      { position: 4, text: "The fourth planet from the Sun, this rusty neighbor of Earth is named for the Roman god of war." },
    ],
    decoys: [
      { text: "Mercury", eliminatedByClue: 2 },
      { text: "Venus", eliminatedByClue: 2 },
    ],
  },
  {
    id: "leonardo-da-vinci",
    answer: "Leonardo da Vinci",
    answerCanonical: "leonardo da vinci",
    answerAliases: ["da Vinci", "Leonardo"],
    category: "Art",
    difficulty: "medium",
    clues: [
      { position: 1, text: "He filled thousands of notebook pages with mirror writing, legible only when held up to a looking glass." },
      { position: 2, text: "A left-handed vegetarian, he sketched helicopters, tanks, and diving suits centuries before they could be built — and left many paintings unfinished." },
      { position: 3, text: "A defining genius of the Italian Renaissance, he painted a fresco of the Last Supper that began flaking off a Milan wall almost at once." },
      { position: 4, text: "This polymath's best-known work is a small portrait of a faintly smiling woman that hangs in the Louvre." },
    ],
    decoys: [
      { text: "Michelangelo", eliminatedByClue: 2 },
      { text: "Raphael", eliminatedByClue: 3 },
    ],
  },
  {
    id: "mona-lisa",
    answer: "Mona Lisa",
    answerCanonical: "mona lisa",
    answerAliases: ["La Gioconda", "La Joconde"],
    category: "Art",
    difficulty: "medium",
    clues: [
      { position: 1, text: "In 1911 a museum handyman walked out with it under his coat, and the bare wall it left behind drew even bigger crowds." },
      { position: 2, text: "Painted on a panel of poplar wood, this small portrait now sits behind bulletproof glass and is far tinier than most visitors expect." },
      { position: 3, text: "The sitter's ambiguous half-smile — and her missing eyebrows — have fueled centuries of speculation." },
      { position: 4, text: "Leonardo da Vinci's most celebrated portrait, it is the star attraction of the Louvre in Paris." },
    ],
    decoys: [
      { text: "The Night Watch", eliminatedByClue: 2 },
      { text: "Girl with a Pearl Earring", eliminatedByClue: 4 },
    ],
  },
  {
    id: "vincent-van-gogh",
    answer: "Vincent van Gogh",
    answerCanonical: "vincent van gogh",
    answerAliases: ["van Gogh"],
    category: "Art",
    difficulty: "medium",
    clues: [
      { position: 1, text: "He sold almost nothing while alive, yet poured out some 2,000 works in barely a decade." },
      { position: 2, text: "Tormented by mental illness, this Dutch painter famously cut off part of his own ear." },
      { position: 3, text: "His thick, swirling brushstrokes and blazing yellows fill canvases like 'Sunflowers' and a whirling night sky over a village." },
      { position: 4, text: "This red-haired Post-Impressionist, who painted 'The Starry Night,' died largely unknown and is now among the most beloved artists ever." },
    ],
    decoys: [
      { text: "Claude Monet", eliminatedByClue: 2 },
      { text: "Paul Gauguin", eliminatedByClue: 4 },
    ],
  },
  {
    id: "albert-einstein",
    answer: "Albert Einstein",
    answerCanonical: "albert einstein",
    answerAliases: ["Einstein"],
    category: "Science",
    difficulty: "medium",
    clues: [
      { position: 1, text: "His most famous theory never won him a Nobel Prize — the award instead cited his work on the photoelectric effect." },
      { position: 2, text: "This German-born physicist was offered the presidency of Israel in 1952 and politely declined." },
      { position: 3, text: "His theories of relativity overturned how we picture space, time, and gravity in the early 20th century." },
      { position: 4, text: "Known for the equation E=mc² and a mane of wild white hair, his surname is now shorthand for 'genius.'" },
    ],
    decoys: [
      { text: "Isaac Newton", eliminatedByClue: 3 },
      { text: "Stephen Hawking", eliminatedByClue: 2 },
    ],
  },
  {
    id: "isaac-newton",
    answer: "Isaac Newton",
    answerCanonical: "isaac newton",
    answerAliases: ["Newton"],
    category: "Science",
    difficulty: "medium",
    clues: [
      { position: 1, text: "He poured as many years into alchemy and biblical prophecy as into physics, and once ran a nation's mint, hanging counterfeiters." },
      { position: 2, text: "A prickly Englishman, he devised calculus around the same time as Leibniz, igniting a bitter priority feud." },
      { position: 3, text: "His three laws describe how objects move, and legend says a falling apple set off his thinking about gravity." },
      { position: 4, text: "This 17th-century scientist's masterwork, the 'Principia,' laid out universal gravitation; the SI unit of force carries his name." },
    ],
    decoys: [
      { text: "Galileo Galilei", eliminatedByClue: 2 },
      { text: "Albert Einstein", eliminatedByClue: 4 },
    ],
  },
  {
    id: "marie-curie",
    answer: "Marie Curie",
    answerCanonical: "marie curie",
    answerAliases: ["Curie", "Madame Curie"],
    category: "Science",
    difficulty: "medium",
    clues: [
      { position: 1, text: "She remains the only person ever to win Nobel Prizes in two different sciences." },
      { position: 2, text: "Her century-old notebooks are still so radioactive that they are stored in lead-lined boxes and handled with protective gear." },
      { position: 3, text: "Born in Poland and working in France, she discovered the elements polonium and radium." },
      { position: 4, text: "A pioneer of radioactivity, she was the first woman to win a Nobel Prize; her daughter Irène later earned one too." },
    ],
    decoys: [
      { text: "Rosalind Franklin", eliminatedByClue: 3 },
      { text: "Lise Meitner", eliminatedByClue: 1 },
    ],
  },
  {
    id: "mount-everest",
    answer: "Mount Everest",
    answerCanonical: "mount everest",
    answerAliases: ["Everest", "Sagarmatha", "Chomolungma"],
    category: "Geography",
    difficulty: "medium",
    clues: [
      { position: 1, text: "Its summit is not actually the spot on Earth's surface farthest from the planet's center — a peak in Ecuador wins that on a technicality." },
      { position: 2, text: "It creeps a few millimeters higher each year as two plates grind together, and its top sits in the 'death zone,' where the air is too thin to survive for long." },
      { position: 3, text: "Sitting on the border of Nepal and Tibet, it was first conquered in 1953 by Edmund Hillary and Tenzing Norgay." },
      { position: 4, text: "At about 8,849 meters, this Himalayan giant is the highest mountain on Earth above sea level." },
    ],
    decoys: [
      { text: "K2", eliminatedByClue: 3 },
      { text: "Mauna Kea", eliminatedByClue: 4 },
    ],
  },
  {
    id: "sahara-desert",
    answer: "Sahara Desert",
    answerCanonical: "sahara desert",
    answerAliases: ["Sahara", "the Sahara"],
    category: "Geography",
    difficulty: "medium",
    clues: [
      { position: 1, text: "Dust lifted from it blows clear across the Atlantic to fertilize the Amazon rainforest thousands of miles away." },
      { position: 2, text: "Roughly the size of the United States, it was dotted with lakes and grazing herds only a few thousand years ago." },
      { position: 3, text: "Sprawling across North Africa, it can broil by day and freeze by night, and has even seen a dusting of snow." },
      { position: 4, text: "This is the largest hot desert on Earth, its name meaning simply 'desert' in Arabic." },
    ],
    decoys: [
      { text: "Gobi Desert", eliminatedByClue: 3 },
      { text: "Kalahari Desert", eliminatedByClue: 4 },
    ],
  },
  {
    id: "antarctica",
    answer: "Antarctica",
    answerCanonical: "antarctica",
    answerAliases: [],
    category: "Geography",
    difficulty: "medium",
    clues: [
      { position: 1, text: "Technically the largest desert on the planet, it gets almost no precipitation despite being smothered in ice." },
      { position: 2, text: "No nation owns it, and it has no permanent residents — only rotating crews of scientists." },
      { position: 3, text: "It locks up about 70% of the world's fresh water as ice, and the coldest temperature ever recorded on Earth was measured here." },
      { position: 4, text: "Home to emperor penguins and the South Pole, it is the southernmost continent." },
    ],
    decoys: [
      { text: "Greenland", eliminatedByClue: 2 },
      { text: "The Arctic", eliminatedByClue: 4 },
    ],
  },
  {
    id: "niagara-falls",
    answer: "Niagara Falls",
    answerCanonical: "niagara falls",
    answerAliases: ["Niagara"],
    category: "Geography",
    difficulty: "medium",
    clues: [
      { position: 1, text: "In 1901 a 63-year-old schoolteacher rode over it sealed inside a wooden barrel — and lived." },
      { position: 2, text: "It briefly ran nearly dry in 1969 when engineers dammed its river to study the eroding rock face." },
      { position: 3, text: "Sitting on the border between the United States and Canada, it lures honeymooners and daredevils in equal measure." },
      { position: 4, text: "This trio of waterfalls, including Horseshoe Falls, straddles New York and Ontario and is among the most famous on Earth." },
    ],
    decoys: [
      { text: "Victoria Falls", eliminatedByClue: 3 },
      { text: "Angel Falls", eliminatedByClue: 4 },
    ],
  },
  {
    id: "great-barrier-reef",
    answer: "Great Barrier Reef",
    answerCanonical: "great barrier reef",
    answerAliases: ["the Great Barrier Reef"],
    category: "Nature",
    difficulty: "medium",
    clues: [
      { position: 1, text: "It is the largest structure on Earth made by living creatures, and is visible from space." },
      { position: 2, text: "Built by billions of tiny coral polyps over thousands of years, it turns ghostly white when warming seas make it 'bleach.'" },
      { position: 3, text: "Running more than 2,300 kilometers off the coast of Queensland, Australia, it shelters clownfish, sea turtles, and reef sharks." },
      { position: 4, text: "This is the world's largest coral reef system, lying off Australia's northeastern shore." },
    ],
    decoys: [
      { text: "Amazon Rainforest", eliminatedByClue: 2 },
      { text: "Belize Barrier Reef", eliminatedByClue: 3 },
    ],
  },
  {
    id: "grand-canyon",
    answer: "Grand Canyon",
    answerCanonical: "grand canyon",
    answerAliases: [],
    category: "Geography",
    difficulty: "easy",
    clues: [
      { position: 1, text: "Its walls expose nearly two billion years of Earth's past, yet the chasm itself was cut in only the last few million." },
      { position: 2, text: "Carved by the Colorado River in Arizona, it plunges more than a mile deep in places." },
      { position: 3, text: "A national park draws millions each year to watch the shifting light paint its banded red cliffs." },
      { position: 4, text: "This vast Arizona gorge, one of the Seven Natural Wonders of the World, is famed for its sheer size and layered walls." },
    ],
    decoys: [
      { text: "Zion Canyon", eliminatedByClue: 4 },
      { text: "Yosemite Valley", eliminatedByClue: 2 },
    ],
  },
  {
    id: "eiffel-tower",
    answer: "Eiffel Tower",
    answerCanonical: "eiffel tower",
    answerAliases: ["the Eiffel Tower"],
    category: "Landmarks",
    difficulty: "easy",
    clues: [
      { position: 1, text: "It stands more than 15 centimeters taller in summer, when the heat makes its iron expand." },
      { position: 2, text: "Built as a temporary showpiece for an 1889 world's fair, it was nearly scrapped but survived because it made a superb radio antenna." },
      { position: 3, text: "Its wrought-iron lattice is repainted every few years to hold back rust, and it towers over a European capital's skyline." },
      { position: 4, text: "This latticed iron landmark, raised for the 1889 Exposition in Paris, is one of the most visited monuments on Earth and a symbol of France." },
    ],
    decoys: [
      { text: "Empire State Building", eliminatedByClue: 3 },
      { text: "Statue of Liberty", eliminatedByClue: 4 },
    ],
  },
  {
    id: "colosseum",
    answer: "Colosseum",
    answerCanonical: "colosseum",
    answerAliases: ["the Colosseum", "Coliseum"],
    category: "Landmarks",
    difficulty: "medium",
    clues: [
      { position: 1, text: "It could reportedly be flooded to stage mock naval battles for the roaring crowds." },
      { position: 2, text: "Raised nearly 2,000 years ago, this vast stone arena packed in tens of thousands to watch gladiators fight." },
      { position: 3, text: "Battered by earthquakes and quarried for its stone over the centuries, its ruins still loom over a famous Italian capital." },
      { position: 4, text: "This ancient oval amphitheater is the single most iconic monument of Rome." },
    ],
    decoys: [
      { text: "Circus Maximus", eliminatedByClue: 1 },
      { text: "Pantheon", eliminatedByClue: 2 },
    ],
  },
  {
    id: "statue-of-liberty",
    answer: "Statue of Liberty",
    answerCanonical: "statue of liberty",
    answerAliases: ["Lady Liberty", "the Statue of Liberty"],
    category: "Landmarks",
    difficulty: "easy",
    clues: [
      { position: 1, text: "A gift between two nations, its copper skin was a shiny reddish brown before weather turned it the green we know." },
      { position: 2, text: "Its internal framework was engineered with help from Gustave Eiffel, and it crossed the Atlantic packed in 350 pieces." },
      { position: 3, text: "Rising from an island in New York Harbor, she lifts a torch in one hand and cradles a tablet marked with a date in Roman numerals." },
      { position: 4, text: "This robed figure, France's gift to America, greeted generations of immigrants sailing into New York." },
    ],
    decoys: [
      { text: "Christ the Redeemer", eliminatedByClue: 3 },
      { text: "Colossus of Rhodes", eliminatedByClue: 4 },
    ],
  },
  {
    id: "taj-mahal",
    answer: "Taj Mahal",
    answerCanonical: "taj mahal",
    answerAliases: ["the Taj Mahal"],
    category: "Landmarks",
    difficulty: "medium",
    clues: [
      { position: 1, text: "It seems to shift color through the day — blushing pink at dawn, white at noon, and golden by moonlight." },
      { position: 2, text: "A grieving emperor built it as a tomb for his beloved wife; some 20,000 workers labored on it for about two decades." },
      { position: 3, text: "Perfectly symmetrical and clad in white marble inlaid with gemstones, it rests beside the Yamuna River in Agra, India." },
      { position: 4, text: "This 17th-century mausoleum is India's most famous building and a jewel of Mughal architecture." },
    ],
    decoys: [
      { text: "Red Fort", eliminatedByClue: 2 },
      { text: "Angkor Wat", eliminatedByClue: 3 },
    ],
  },
  {
    id: "kangaroo",
    answer: "Kangaroo",
    answerCanonical: "kangaroo",
    answerAliases: ["kangaroos"],
    category: "Animals",
    difficulty: "easy",
    clues: [
      { position: 1, text: "It physically cannot walk backward, and springy tendons let it bound faster while burning less energy." },
      { position: 2, text: "A newborn is the size of a jellybean and hauls itself into its mother's pouch to keep developing." },
      { position: 3, text: "This marsupial props itself on a thick muscular tail like a fifth limb and can throw a bruising kick." },
      { position: 4, text: "Australia's famous hopping icon, the males are called boomers and the babies are joeys." },
    ],
    decoys: [
      { text: "Koala", eliminatedByClue: 1 },
      { text: "Wallaby", eliminatedByClue: 4 },
    ],
  },
  {
    id: "giant-panda",
    answer: "Giant Panda",
    answerCanonical: "giant panda",
    answerAliases: ["panda", "pandas"],
    category: "Animals",
    difficulty: "easy",
    clues: [
      { position: 1, text: "Though its gut is built like a meat-eater's, it spends up to 14 hours a day munching almost nothing but bamboo." },
      { position: 2, text: "A newborn is pink, hairless, and about the size of a stick of butter — roughly a nine-hundredth of its mother's weight." },
      { position: 3, text: "A 'thumb' formed from an enlarged wrist bone helps it grip stalks, and China lends these black-and-white bears to zoos abroad." },
      { position: 4, text: "This bamboo-eating bear from China's misty highlands is the black-and-white emblem of the WWF." },
    ],
    decoys: [
      { text: "Polar Bear", eliminatedByClue: 1 },
      { text: "Red Panda", eliminatedByClue: 3 },
    ],
  },
  {
    id: "chameleon",
    answer: "Chameleon",
    answerCanonical: "chameleon",
    answerAliases: ["chameleons"],
    category: "Animals",
    difficulty: "medium",
    clues: [
      { position: 1, text: "Its two eyes can swivel and aim in entirely different directions at the same instant." },
      { position: 2, text: "It fires out a tongue longer than its own body to snatch an insect, striking in a fraction of a second." },
      { position: 3, text: "Many species shift color less for camouflage than to broadcast mood and temperature, by rearranging tiny crystals in their skin." },
      { position: 4, text: "This lizard, with many kinds native to Madagascar, is famous for changing color and clamping onto branches with pincer-like feet." },
    ],
    decoys: [
      { text: "Gecko", eliminatedByClue: 3 },
      { text: "Octopus", eliminatedByClue: 4 },
    ],
  },
  {
    id: "honeybee",
    answer: "Honeybee",
    answerCanonical: "honeybee",
    answerAliases: ["honey bee", "honeybees", "honey-bee"],
    category: "Animals",
    difficulty: "easy",
    clues: [
      { position: 1, text: "It tells its sisters exactly where to find food by performing a looping 'waggle dance.'" },
      { position: 2, text: "A female worker can strike only once, because her barbed stinger tears free and the wound kills her." },
      { position: 3, text: "Living in colonies tens of thousands strong under a single queen, these insects build wax combs of six-sided cells." },
      { position: 4, text: "This buzzing pollinator turns flower nectar into the golden syrup we drizzle on toast." },
    ],
    decoys: [
      { text: "Wasp", eliminatedByClue: 4 },
      { text: "Bumblebee", eliminatedByClue: 2 },
    ],
  },
  {
    id: "elephant",
    answer: "Elephant",
    answerCanonical: "elephant",
    answerAliases: ["elephants"],
    category: "Animals",
    difficulty: "easy",
    clues: [
      { position: 1, text: "It is the only land mammal that cannot jump, yet it can 'hear' distant rumbles through the soles of its feet." },
      { position: 2, text: "Talking in calls too deep for us to hear, it can recognize itself in a mirror and seems to grieve over its dead." },
      { position: 3, text: "The largest land animal alive, it breathes, drinks, and grabs food with a long trunk packed with tens of thousands of muscles." },
      { position: 4, text: "This gray giant, with big flapping ears and ivory tusks, comes in African and Asian kinds." },
    ],
    decoys: [
      { text: "Rhinoceros", eliminatedByClue: 3 },
      { text: "Hippopotamus", eliminatedByClue: 4 },
    ],
  },
  {
    id: "coffee",
    answer: "Coffee",
    answerCanonical: "coffee",
    answerAliases: [],
    category: "Food & Drink",
    difficulty: "easy",
    clues: [
      { position: 1, text: "Legend credits its discovery to an Ethiopian goatherd who saw his flock dancing after nibbling certain red berries." },
      { position: 2, text: "One of the most heavily traded commodities on Earth, its 'beans' are really the roasted seeds of a fruit." },
      { position: 3, text: "Once banned in several places for its stimulating kick, it is pulled into espresso, cappuccino, and latte." },
      { position: 4, text: "This caffeinated morning brew, made from roasted ground beans, comes in Arabica and Robusta types." },
    ],
    decoys: [
      { text: "Tea", eliminatedByClue: 4 },
      { text: "Cocoa", eliminatedByClue: 3 },
    ],
  },
  {
    id: "chocolate",
    answer: "Chocolate",
    answerCanonical: "chocolate",
    answerAliases: [],
    category: "Food & Drink",
    difficulty: "easy",
    clues: [
      { position: 1, text: "The ancient Maya and Aztecs drank it bitter and spiced, and even used its beans as money." },
      { position: 2, text: "Pressed from the fermented, roasted seeds of a tropical tree, it melts at just below human body temperature." },
      { position: 3, text: "Poisonous to dogs thanks to a compound called theobromine, it is sold in dark, milk, and white forms." },
      { position: 4, text: "This sweet treat, made from cacao, fills Easter eggs and Valentine's boxes." },
    ],
    decoys: [
      { text: "Coffee", eliminatedByClue: 2 },
      { text: "Vanilla", eliminatedByClue: 4 },
    ],
  },
  {
    id: "the-beatles",
    answer: "The Beatles",
    answerCanonical: "the beatles",
    answerAliases: ["Beatles", "the Fab Four", "Fab Four"],
    category: "Music",
    difficulty: "easy",
    clues: [
      { position: 1, text: "A record label turned them down in 1962, declaring that guitar groups were 'on the way out.'" },
      { position: 2, text: "This four-piece from a northern English port city still holds the record for the most number-one hits on the U.S. charts." },
      { position: 3, text: "Made up of John, Paul, George, and Ringo, they quit touring in 1966 to pour themselves into studio albums like 'Sgt. Pepper.'" },
      { position: 4, text: "This Liverpool rock band of the 1960s recorded 'Hey Jude' and 'Let It Be.'" },
    ],
    decoys: [
      { text: "The Rolling Stones", eliminatedByClue: 3 },
      { text: "The Beach Boys", eliminatedByClue: 4 },
    ],
  },
  {
    id: "beethoven",
    answer: "Ludwig van Beethoven",
    answerCanonical: "ludwig van beethoven",
    answerAliases: ["Beethoven"],
    category: "Music",
    difficulty: "medium",
    clues: [
      { position: 1, text: "He wrote some of his greatest music, including his final symphony, while almost completely deaf." },
      { position: 2, text: "This German composer sawed the legs off his piano so he could feel its vibrations through the floor as his hearing failed." },
      { position: 3, text: "A bridge from the Classical to the Romantic era, his Fifth Symphony opens with four of the most famous notes in music: da-da-da-DUM." },
      { position: 4, text: "This wild-haired composer's Ninth Symphony gave the world the 'Ode to Joy.'" },
    ],
    decoys: [
      { text: "Wolfgang Amadeus Mozart", eliminatedByClue: 2 },
      { text: "Johann Sebastian Bach", eliminatedByClue: 4 },
    ],
  },
  {
    id: "chess",
    answer: "Chess",
    answerCanonical: "chess",
    answerAliases: [],
    category: "Games",
    difficulty: "medium",
    clues: [
      { position: 1, text: "The number of possible games it allows outstrips the count of atoms in the observable universe." },
      { position: 2, text: "Descended from the Indian game 'chaturanga' some 1,500 years ago, its most powerful piece was once feeble until European players supercharged her." },
      { position: 3, text: "Fought over 64 light and dark squares, its goal is to trap the enemy king in 'checkmate.'" },
      { position: 4, text: "In this two-player strategy game, each side marshals pawns, knights, bishops, rooks, a queen, and a king." },
    ],
    decoys: [
      { text: "Checkers", eliminatedByClue: 4 },
      { text: "Go", eliminatedByClue: 3 },
    ],
  },
  {
    id: "tokyo",
    answer: "Tokyo",
    answerCanonical: "tokyo",
    answerAliases: [],
    category: "Cities",
    difficulty: "easy",
    clues: [
      { position: 1, text: "As many as 3,000 people flood across its busiest pedestrian scramble every time the light turns." },
      { position: 2, text: "Once a fishing village called Edo, it grew into one of the world's biggest cities by the 1700s; its modern name means 'eastern capital.'" },
      { position: 3, text: "The most populous metropolitan area on the planet, it hosted the Summer Olympics in 1964 and again in 2021." },
      { position: 4, text: "This bustling Japanese capital is home to the Shibuya crossing and the Emperor's Imperial Palace." },
    ],
    decoys: [
      { text: "Kyoto", eliminatedByClue: 2 },
      { text: "Osaka", eliminatedByClue: 4 },
    ],
  },
  {
    id: "blue-whale",
    answer: "Blue Whale",
    answerCanonical: "blue whale",
    answerAliases: [],
    category: "Animals",
    difficulty: "easy",
    clues: [
      { position: 1, text: "A nursing newborn packs on roughly the weight of an adult human every single day." },
      { position: 2, text: "Its heart alone is about the size of a small car, and its low moans are the loudest sounds made by any animal." },
      { position: 3, text: "For all its bulk, it lives almost entirely on tiny shrimp-like krill, straining tons of them through fringed plates of baleen." },
      { position: 4, text: "The largest animal ever known to have lived, this baleen whale is named for its bluish-gray color." },
    ],
    decoys: [
      { text: "Sperm Whale", eliminatedByClue: 3 },
      { text: "Whale Shark", eliminatedByClue: 4 },
    ],
  },
  {
    id: "great-white-shark",
    answer: "Great White Shark",
    answerCanonical: "great white shark",
    answerAliases: ["great white"],
    category: "Animals",
    difficulty: "medium",
    clues: [
      { position: 1, text: "Jelly-filled pores on its snout let it sense the faint electric fields of a heartbeat, sniffing out prey hidden in the sand." },
      { position: 2, text: "Warmer-bodied than most fish, it can rocket its whole body clear out of the water to ambush a seal from below." },
      { position: 3, text: "It grows and sheds thousands of serrated teeth over its life, set in replaceable rows, yet has never survived long in a tank." },
      { position: 4, text: "The huge predatory fish behind the movie 'Jaws,' it is named for its pale underside." },
    ],
    decoys: [
      { text: "Killer Whale", eliminatedByClue: 4 },
      { text: "Tiger Shark", eliminatedByClue: 4 },
    ],
  },
  {
    id: "napoleon-bonaparte",
    answer: "Napoleon Bonaparte",
    answerCanonical: "napoleon bonaparte",
    answerAliases: ["Napoleon"],
    category: "History",
    difficulty: "medium",
    clues: [
      { position: 1, text: "The legend that he was unusually short is a myth — a muddle of old French and British units, sharpened by enemy cartoonists." },
      { position: 2, text: "Born on the island of Corsica, he rode the chaos of a revolution all the way to crowning himself emperor in 1804." },
      { position: 3, text: "His sweeping legal code still shapes law around the world, but his empire cracked after a catastrophic invasion of Russia." },
      { position: 4, text: "This French military genius met his final defeat at Waterloo in 1815 and died in exile on St. Helena." },
    ],
    decoys: [
      { text: "Julius Caesar", eliminatedByClue: 4 },
      { text: "Louis XVI", eliminatedByClue: 2 },
    ],
  },
  {
    id: "mount-fuji",
    answer: "Mount Fuji",
    answerCanonical: "mount fuji",
    answerAliases: ["Fuji", "Fujisan"],
    category: "Geography",
    difficulty: "medium",
    clues: [
      { position: 1, text: "Hokusai gave it an entire series of woodblock prints, among them one of a towering, claw-like wave." },
      { position: 2, text: "An active volcano that last erupted in 1707, its near-perfect symmetrical cone is a sacred site that draws hundreds of thousands of climbers each summer." },
      { position: 3, text: "The highest peak in its country at about 3,776 meters, it can be seen from Tokyo on a clear day." },
      { position: 4, text: "This snow-capped volcano is Japan's most famous mountain and a national symbol." },
    ],
    decoys: [
      { text: "Mount Kilimanjaro", eliminatedByClue: 3 },
      { text: "Mount Vesuvius", eliminatedByClue: 3 },
    ],
  },
  {
    id: "machu-picchu",
    answer: "Machu Picchu",
    answerCanonical: "machu picchu",
    answerAliases: ["the Lost City of the Incas"],
    category: "Landmarks",
    difficulty: "medium",
    clues: [
      { position: 1, text: "Its finest stones are cut and fitted so tightly, without any mortar, that a knife blade cannot slip between them." },
      { position: 2, text: "Built around 1450 and abandoned barely a century later, it slipped past the Spanish conquistadors entirely." },
      { position: 3, text: "Perched on a ridge high in the Peruvian Andes, it was brought to the world's attention by explorer Hiram Bingham in 1911." },
      { position: 4, text: "This mist-wrapped stone citadel is the most famous ruin of the Inca Empire." },
    ],
    decoys: [
      { text: "Chichen Itza", eliminatedByClue: 4 },
      { text: "Petra", eliminatedByClue: 3 },
    ],
  },
  {
    id: "the-nile",
    answer: "The Nile",
    answerCanonical: "the nile",
    answerAliases: ["Nile", "Nile River"],
    category: "Geography",
    difficulty: "medium",
    clues: [
      { position: 1, text: "Unlike most great rivers, it runs from south to north, emptying into the Mediterranean Sea." },
      { position: 2, text: "Its yearly floods laid down rich black silt that fed one of the world's earliest civilizations." },
      { position: 3, text: "Its two main branches, the White and the Blue, join at Khartoum in Sudan before the water flows on through Egypt." },
      { position: 4, text: "Often called the longest river on Earth, this African waterway was the lifeblood of ancient Egypt." },
    ],
    decoys: [
      { text: "Amazon River", eliminatedByClue: 1 },
      { text: "Congo River", eliminatedByClue: 3 },
    ],
  },
  {
    id: "charles-darwin",
    answer: "Charles Darwin",
    answerCanonical: "charles darwin",
    answerAliases: ["Darwin"],
    category: "Science",
    difficulty: "medium",
    clues: [
      { position: 1, text: "He sat on his world-changing theory for some twenty years before he dared to publish it." },
      { position: 2, text: "A five-year voyage aboard HMS Beagle — and especially the finches of the Galápagos Islands — reshaped his thinking." },
      { position: 3, text: "This English naturalist argued that living things change over generations through a process he called 'natural selection.'" },
      { position: 4, text: "His 1859 book 'On the Origin of Species' laid out the theory of evolution." },
    ],
    decoys: [
      { text: "Alfred Russel Wallace", eliminatedByClue: 4 },
      { text: "Gregor Mendel", eliminatedByClue: 2 },
    ],
  },
  {
    id: "amelia-earhart",
    answer: "Amelia Earhart",
    answerCanonical: "amelia earhart",
    answerAliases: ["Earhart"],
    category: "History",
    difficulty: "medium",
    clues: [
      { position: 1, text: "She vanished without a trace over the Pacific in 1937, and her fate is still argued about today." },
      { position: 2, text: "Five years earlier, in 1932, she became the first woman to fly solo across the Atlantic Ocean." },
      { position: 3, text: "She disappeared while trying to circle the globe, her plane lost somewhere near tiny Howland Island." },
      { position: 4, text: "This pioneering American aviator remains one of history's most famous missing persons." },
    ],
    decoys: [
      { text: "Charles Lindbergh", eliminatedByClue: 2 },
      { text: "Bessie Coleman", eliminatedByClue: 3 },
    ],
  },
  {
    id: "pizza",
    answer: "Pizza",
    answerCanonical: "pizza",
    answerAliases: [],
    category: "Food & Drink",
    difficulty: "easy",
    clues: [
      { position: 1, text: "Its classic Margherita version was supposedly dreamed up to honor an Italian queen, its red, white, and green echoing the flag." },
      { position: 2, text: "Born among the poor of Naples, it was long a humble street food before it conquered the world." },
      { position: 3, text: "The 'Hawaiian' style, crowned with pineapple, was actually invented in Canada in 1962." },
      { position: 4, text: "This round, oven-baked Italian dish of dough, tomato sauce, and cheese is served in wedges." },
    ],
    decoys: [
      { text: "Focaccia", eliminatedByClue: 3 },
      { text: "Calzone", eliminatedByClue: 4 },
    ],
  },
  {
    id: "basketball",
    answer: "Basketball",
    answerCanonical: "basketball",
    answerAliases: [],
    category: "Sports",
    difficulty: "easy",
    clues: [
      { position: 1, text: "The very first version used a fruit basket with its bottom still in, so someone had to fetch the ball by ladder after every score." },
      { position: 2, text: "Dr. James Naismith invented it in 1891 at a Massachusetts YMCA to keep students active indoors through the winter." },
      { position: 3, text: "Two teams bounce the ball as they move it, aiming to drop it through a hoop set 10 feet above the floor." },
      { position: 4, text: "In this sport, players 'dribble' and 'dunk' to score, and the NBA is its top professional league." },
    ],
    decoys: [
      { text: "Volleyball", eliminatedByClue: 3 },
      { text: "Netball", eliminatedByClue: 4 },
    ],
  },
];
